### ISSUE TITLE
FLEDGE testing: available supply; Current State and Challenges

### ISSUE THREAD

**Issue by piwanczak** [privacysandbox/privacy-sandbox-dev-support#110]
Chrome Privacy Sandbox for Web Origin Trials offer 5% +1% of FLEDGE eligible traffic allowing both adding users to Interest Groups as well as running on-device auctions. 
This issue aims to provide a concise overview of the current state of FLEDGE integration with publishers & inventory suppliers and the challenges faced from RTB House DSP’s point of view. 
We invite all other interested parties to share their point of views and discuss solutions.

**Current Implementation status**

1. Google Ad Manager (GAM) 

  - runs FLEDGE auctions of a small portion of GAM’s publisher inventory (below 1% of traffic) for interested participating buyers - Authorized Buyers & DV360 ([reference](https://support.google.com/admanager/answer/12052605?hl=en))

  - **Issues**:

    - Lack of granular & full control over experiments by publishers and their vendors 

    - Support for multi-ssp auction is partially available using GAM's experimental API, but Publishers have no control over auction volume and have limited capabilities to monitor the status of experiments. Ie: currently, there is no way for the publisher to configure FLEDGE to run on 100% of FLEDGE eligible traffic, on a page - for internal QA tests or larger scale tests

    - It is unclear if Google's demand will take part as a Component Auction in 3rd party FLEDGE auctions (non-GAM FLEDGE implementations) - link https://github.com/google/ads-privacy/issues/65#issuecomment-1237767847

2. Prebid

  - Currently we know of no live FLEDGE traffic available through Prebid’s implementation yet

  - Prebid has experimental [FLEDGE for GPT module](https://docs.prebid.org/dev-docs/modules/fledgeForGpt.html) that potentially allows participation in FLEDGE tests through GAM’s experimental API for multi ssp setup, thanks to OpenX code submission

  - There are two “adapters” that show signs of FLEDGE support through said module. Adapter in Prebid’s nomenclature it’s an alias for demand source that could be a sell side platform (SSP) or a bidder (DSP)

  - There is no Prebid implementation with Prebid acting as FLEDGE top level auction; Current implementation relies on GAM’s experimental API

  - **Issues**:

    - FLEDGE for GPT relies on GAM’s tooling - publisher or its vendor faces the same challenges as with potentially working through GAM’s experimental API directly, ie cannot on its own set up and control FLEDGE volumes on its properties

    - Prebid is yet to propose non-GAM FLEDGE implementation, without direct reliance on GAM FLEDGE API

**Challenges**

- As a DSP we face challenges getting larger volumes of FLEDGE eligible traffic

- GAM FLEDGE send a portion of FLEDGE-eligible traffic only (below 1% of traffic - reference: https://support.google.com/admanager/answer/12052605?hl=en)

- There seems to be no FLEDGE testing possibilities for publishers or pub vendors that do not use GAM yet

**Comment by clementsimon** [comment]
Closing as the Origin Trial has ended and the Protected Audience API is now generally available.
