### ISSUE TITLE
Are you planning to test using Mode A, Mode B, or both?

### ISSUE THREAD

**Issue by rowan-m** [privacysandbox/privacy-sandbox-dev-support#112]
See https://developer.chrome.com/docs/privacy-sandbox/chrome-testing/ for details where:

- **Mode A**: Ad techs can receive control and experiment labels on a portion of traffic and use these to conduct testing and experiments.
**Mode B**: Chrome globally disables third-party cookies for some portion of all Chrome users.

**Comment by dmdabbs** [comment]
The [Chrome-facilitated testing](https://developer.chrome.com/docs/privacy-sandbox/chrome-testing/#mode-b) doc says:

>Additionally, we plan to provide a small fraction of traffic within Mode B that has Privacy Sandbox relevance and measurement APIs disabled.  Other APIs, like First-Party Sets, CHIPS, FedCM, and so on, will not be disabled.

Is it correct to infer that we can count on all Sandbox features to be enabled on all Mode B instances, modulo this small holdout/control group? Of course some users may disable using the new privacy UX or sites disable using Permission policy.

**Comment by dmdabbs** [comment]
The [Chrome-facilitated testing](https://developer.chrome.com/blog/shipping-privacy-sandbox/#shipping-features-in-chrome) doc says of the features anticipated to ship in Chrome 115,

>The APIs will not immediately be enabled for all browser instances with the Stable release. As with some previous Privacy Sandbox features, we'll gradually enable the APIs for an increasing percentage of browser instances to ensure that we can monitor and respond to any potential issues.

and later about [Mode A](https://developer.chrome.com/blog/shipping-privacy-sandbox/#mode-a),

>We anticipate providing labels for up to 10% of Chrome browsers....
>We plan to make the opt-in testing mode available starting in Q4 2023, and we'll continue this mode until third-party cookie deprecation.

Will you ensure that the 10% Mode A cohort labeled starting this date have all [relevance and measurement APIs](https://developer.chrome.com/blog/shipping-privacy-sandbox/#whats-shipping) enabled? 

Will any consideration be given to allocating the cohort across mobile versus desktop?

**Comment by jdwieland8282** [comment]
Same question as above, when should we expect to start seeing cohort labels? Will we see them prior to the test 3p cookie deprecation?

**Comment by piwanczak** [comment]
We plan on participating in both. It would be great if Mode A was to be sent even earlier than Q4

**Comment by rowan-m** [comment]
Appreciate the comments! We published https://developer.chrome.com/blog/privacy-sandbox-launch/#chrome-facilitated-testing-modes just recently and in there we're now on for providing an update on the testing modes in mid-August. I believe we are still on track for Q4 with the labels, though I'll certainly share the feedback that there's appetite for them sooner rather than later. The labels will definitely be appearing before the one percent cookie deprecation, which is scheduled for Q1.

**Comment by rowan-m** [comment]
@dmdabbs I'll validate both of these, but my initial thinking is:

> Will we be able to count on the 10% Mode A cohort labeled by that date having all [relevance and measurement APIs](https://developer.chrome.com/blog/shipping-privacy-sandbox/#whats-shipping) enabled?

I think the cohorts are intended to be relatively stable, which means that while the APIs should be available to the entire group, users can still turn them off or on via the controls. I believe the goal is to provide a group where testers can coordinate to not use third-party cookies on a stable population. So in that sense, it would be similar to the population after third-party cookie deprecation, where users still have the option of turning the APIs on or off.

> Will any consideration be given to allocating the cohort across mobile versus desktop?

My current understanding is that these groups will be applied evenly across Android and desktop.

**Comment by Solgarcia912** [comment]
{"cplatform":"mobile","cff":"SMALL_FORM_FACTOR","c":"android_music","cplayer":"ANDROID_EXOPLAYER_V2","cmodel":"ZTE A7050","cos":"Android","soc":"Spreadtrum:T616","cver":"6.28.53","cbrand":"ZTE","cbr":"com.google.android.apps.youtube.music","csdk":"31","cbrver":"6.28.53","cosver":"12.SP1A.210812.016.20230914.103140","videoid":"fGJhIHgOqJQ","cpn":"Y9RFoH-flUFznSVN","fmt":"N\/A","afmt":"251 opus","bh":1958,"conn":10,"volume":86,"loudness":"-2.970","bat":"0.370:0","df":"0\/0","time":"2023-12-02T04:10:55.774Z","glmode":"RECTANGULAR_2D","drm":"","mtext":"G","error":"No errors","logged_in":"1","e":"9453588,9453589,23946420,23966208,23983296,23998056,24004644,24007246,24034168,24036947,24077241,24078649,24080738,24120819,24135310,24140247,24181174,24187377,24241378,24255543,24255545,24265964,24285788,24288664,24290971,24367580,24367699,24371778,24377598,24377909,24382552,24385728,24390675,24428788,24428941,24428945,24451319,24458317,24458324,24458329,24458839,24468724,24469241,24485421,24489305,24515423,24518452,24522280,24524098,24525682,24526515,24526642,24526770,24526787,24526794,24526797,24526808,24526811,24526827,24528550,24528555,24528575,24528580,24528640,24528651,24528661,24528666,24537200,24537905,24540881,24542367,24542452,24545211,24546060,24546075,24548627,24548629,24549786,24552798,24555431,24556101,24559327,24560416,24560687,24561210,24561384,24563005,24563746,24566293,24583801,24585907,24588588,24588590,24589493,24694842,24697067,24698452,39324156,39325366,51003636,51004018,51006175,51009757,51009781,51009900,51010008,51010579,51012291,51012659,51014091,51016856,51017346,51019626,51020240,51020404,51020570,51021953,51022793,51025415,51025833,51027870,51029412,51030101,51031447,51033399,51033484,51033577,51036438,51036511,51037088,51037136,51037342,51037353,51037540,51040388,51041331,51041497,51042257,51043057,51043948,51044723,51045888,51045969,51047534,51047541,51047579,51047827,51048489,51049006,51050630,51052603,51052608,51053957,51054675,51055016,51055107,51055917,51056263,51056270,51057746,51057811,51057822,51057848,51057851,51058994,51059322,51059545,51059572,51060024,51061018,51061427,51061926,51062179,51063129,51063134,51063151,51063162,51063326,51065187,51066749,51068528,51068753,51068868,51069319,51069390,51070193,51071180,51071836,51073668,51073900,51074511,51076081,51076170"}

**Comment by rowan-m** [comment]
Closing out as we've ended the Chrome-facilitated testing period.

**Comment by validpower** [comment]
I wanted to see my girlfriend's cell phone but I didn't know they would break in, sorry.
