### ISSUE TITLE
Will there be a way for a SharedWorker to send a fetch request with CHIPS cookies?

### ISSUE THREAD

**Issue by bretticus-mc** [privacysandbox/privacy-sandbox-dev-support#127]
Today a SharedWorker for an embedded iframe can send a fetch with credentials:include that includes unpartitioned cookies. However, when I set a partitioned Cookie, the SharedWorker's fetch does not include the partitioned cookie. This is a significant degradation in the functionality of SharedWorkers, particularly when it comes to contacting endpoints that require authentication cookies. Is this intended? It seems like a bug. 

From my testing, an embedded Iframe's SharedWorker is already partitioned by top-level site. If I have tab1 with SiteA embedded in top-level siteB, and tab2 with SiteA embedded in top-level siteC, there will be two Shared Workers for SiteA. Therefore, I don't see what this solves by not allowing SharedWorkers access to cookies.

**Comment by arichiv** [comment]
Wanted to give a heads up that the Storage Access API extension OT is adding Shared Worker support in M123: https://developers.google.com/privacy-sandbox/blog/saa-non-cookie-storage
