### ISSUE TITLE
Cross-origin joinAdInterestGroup generates warnings.

### ISSUE THREAD

**Issue by michal-kalisz** [privacysandbox/privacy-sandbox-dev-support#132]
Hi,

When we call joinAdInterestGroup inside a cross-origin iframe, we receive a warning:

```
In the future, the Permissions Policy feature join-ad-interest-group will not be enabled by default in cross-origin iframes or same-origin iframes nested in cross-origin iframes. Calling joinAdInterestGroup will be rejected with a NotAllowedError if it is not explicitly enabled.
```

Even if we grant the necessary permissions through the allow attribute:
```
<iframe src="..." allow="join-ad-interest-group;run-ad-auction" />
```
However, enabling a more restrictive flag, _--enable-features=AdInterestGroupAPIRestrictedPolicyByDefault_, prevents the warning from appearing.

Is this the expected behaviour?
Is it possible to prevent the warning from appearing while still calling joinAdInterestGroup inside a cross-domain iframe?

Thanks in advance,
Michal

**Comment by clementsimon** [comment]
The warning should now only appear if the cross-origin iframe does not have the appropriate Permissions Policy in place. Closing.
