### ISSUE TITLE
Can this be used to exchange data between isolated-app: and an arbitrary window?

### ISSUE THREAD

**Issue by guest271314** [privacysandbox/privacy-sandbox-dev-support#147]
Just came across this while examing the properties defined on `globalThis` in an Isolated Web App.  

Right now I'm using File System Access API and a WebRTC Data Channel  to communicate between the Isolated Web APP (IWA) and the arbitrary Web page that opens the `window` where the `isolated-app:` URL is loaded. 

Ideally we, the developer/end-user could just specify which origins `opener` will be set for when the IWA is opened. However, that is not something IWA proposal authors are apparently interested in providing to end-users.

Can this be used to exchange data and objects (I'm thinking about using transferable streams here) between `isolated-app:` and an arbitrary `window`?

**Comment by samdutton** [comment]
Apologies for the delay in responding — just realised noone replied to this.

This is really outside the threat model for Privacy Sandbox, as it requires the user to pass data between two origins via some out-of-band mechanism.

You've probably dealt with this already by now, but you may be able to get further guidance on the [discuss-webrtc](https://groups.google.com/g/discuss-webrtc) group.

**Comment by guest271314** [comment]
I was referring to [Shared Storage context](https://developers.google.com/privacy-sandbox/relevance/fenced-frame), e.g.,  [Simple example: Consistent A/B experiments across sites](https://github.com/WICG/shared-storage). 

Specifically since `isolated-app:` is cross-origin isolated and has no `opener` I was trying to see if I could transfer data,i.e., transferable objects, to and from the Isolated Web App window as `ArrayBuffer`. 

The WICG File System Access API and WebRTC `RTCDataChannel` version I wrote works, just requires a few steps. I was using `window.open()` initially, then IWA owners decided to block opening `isolated-app:` windows from DevTools console. https://github.com/guest271314/telnet-client/blob/user-defined-tcpsocket-controller-web-api/direct-sockets/direct-socket-controller.js#L53-L68

```
      // https://issues.chromium.org/issues/339994757#comment6
      /*
      var w = open(
        `IWA_URL?sdp=${
          btoa(local.localDescription.sdp)
        }`,
      );
      */
      const params = new URLSearchParams();
      params.set("sdp", btoa(local.localDescription.sdp));
      params.set("name", "Signed Web Bundle in Isolated Web App");
      if (globalThis?.openIsolatedWebApp) {
        openIsolatedWebApp(`?${params.toString()}`);
      } else {
        setTitle(`?${params.toString()}`);
      }
```
Now I use an extension to open the window https://github.com/guest271314/isolated-web-app-utilities/blob/main/background.js#L121C1-L145. My goal was to do this using only Web API's if possible, standalone from a browser extension version.

```
// Open IWA window
async function openIsolatedWebApp(
  webAppDetails,
  isolatedWebAppName,
  detail = "",
) {
  try {
    console.log(isolatedWebAppName, detail);
    const url = webAppDetails.find((webapp) =>
      webapp["!name"] === isolatedWebAppName
    )
      .start_url;
    return await chrome.windows.create({
      url: `${url}${detail}`,
      height: 0,
      width: 0,
      left: 0,
      top: 0,
      focused: false,
      type: "normal",
    });
  } catch (e) {
    console.error(chrome.runtime.lastError, e);
  }
}
```

Looking at your mission statement

> - Develop new features to keep your information private.
> - Enable publishers and developers to keep online content free.
> - Collaborate with the industry to build new internet privacy standards.

I filed an issue here for the prospect of working with developers in the field to facilitate privacy in the case of being able to communicate between contexts the user launches on the users own machine. Thanks.
