### ISSUE TITLE
Chrome-facilitated testing

### ISSUE THREAD

**Issue by dmdabbs** [privacysandbox/privacy-sandbox-dev-support#148]
Thank you for providing [more info](https://developer.chrome.com/en/docs/privacy-sandbox/chrome-testing/#cookie-deprecation-value) about how to access the Chrome-facilitated test labels. 

>For the duration of Mode A and Mode B we will be introducing a temporary Cookie-Deprecation value ... which will provide the label for the browser's applicable Mode A or B experiment group ... if it falls into one. We will remove this value when the experiment ends.

How far in advance will you label a Chrome instance prior to its cookies being suppressed in the 1% Mode B cohort?

`Sec-Cookie-Deprecation: example_label_1`

Do we need to monitor the testing page for revisions, such as details of the labels themselves, or will notification come via blink-dev _Intent_ updates?

**Comment by dmdabbs** [comment]
Requiring all testers to set a Partitioned cookie on every site interaction or to invoke the temporary Promise-based Javascript API seems needlessly complex and wasteful. Just send the labels. Why add impediments to testing?

**Comment by rowan-m** [comment]
I appreciate there's some implementation effort on the site side, but it's necessary to ensure sites have control on whether or not they are receiving that data as per: https://developer.chrome.com/docs/privacy-sandbox/chrome-testing/#cookie-deprecation-value:~:text=Accessing%20labels%20involves,applies%20to%20you.

**Comment by dmdabbs** [comment]
Yes. Ok. 

Your label access via partitioned cookie [implementation](https://bugs.chromium.org/p/chromium/issues/detail?id=1479071) appears to be complete. The proposed Navigator API to follow soon, presumably. 

How about some color regarding the labels themselves. Can you kindly please share a bit beyond `example_label_1`? Or is this implicitly saying that the labels will be self-evident and trivially parsed?

**Comment by rowan-m** [comment]
We now have the details for the label names and percentages available:
https://developer.chrome.com/docs/privacy-sandbox/chrome-testing/#mode-a

**Comment by dmdabbs** [comment]
Thank you @rowan-m for the follow up. I will review.
