### ISSUE TITLE
WebView Attribution Reporting API not sending support header

### ISSUE THREAD

**Issue by taddcrockett** [privacysandbox/privacy-sandbox-dev-support#149]
Hello,

I am trying to test out the app-web use case for the Attribution Reporting API and am unable to enable the WebView in my demo app to support it.

My understanding is that when I register a source to the reporting origin from some HTML shown by the WebView, there should be a header attached Attribution-Reporting-Support: os, web, as detailed [here](https://github.com/WICG/attribution-reporting-api/blob/main/app_to_web.md#api-changes). However there is no such header.

Am I misunderstanding the implementation here or is this not supported on my device.

- Testing on emulator
  - Build number: URD9.230712.002.A1
  - WebView version: Android System WebView Dev 118.0.5977.3
- I have added added the [Cross App and Web Origin Trial token](https://developer.chrome.com/origintrials/#/view_trial/151996487423754241) to the HTML via meta tag in head.
- My app hosting the WebView has [declared AdServices permissions](https://developer.android.com/design-for-safety/privacy-sandbox/setup-api-access?version=beta

Thanks in advance

**Comment by erintwalsh** [comment]
Hello,

Thanks for your patience! If you are not seeing the header, it is likely you don't have the correct permissions set and are not in the WebView trial. Please make sure all the requirements are met:

* Follow all instructions to [set up your device with the correct permissions](https://developer.android.com/design-for-safety/privacy-sandbox/setup-device-access?version=beta)
* Make sure you are using Android UDC 
* Make sure your version of Chrome is above `114.0.5714.0`
* Make sure your version of WebView is above `116.0.5803.0`
* Go to your flags on Chrome by opening `chrome://flags/` and make sure the Privacy Sandbox Ads APIs experiment is enabled
* Make sure you are in the App to Web Origin Trial by going to your [origin trials](https://developer.chrome.com/origintrials/#/trials/active) and registering for `Cross App and Web Attribution Measurement` Trial
* You can force the WebView Trial by setting flags in the [WebView Shell App](https://chromium.googlesource.com/chromium/src/+/HEAD/android_webview/docs/webview-shell.md). Go to the app, select the three dot overflow menu, select "WebView DevTools" > "Flags", then enable the flags `PrivacySandboxAdsAPIsOverride` and `AttributionReportingCrossAppWeb`

Please let us know if you are still seeing errors after following these steps.

**Comment by samdutton** [comment]
There hasn't been any activity on this bug for several months, so I'll close it. Feel free to reopen if necessary.

**Comment by taddcrockett** [comment]
@erintwalsh still no luck. 

- Follow all instructions to [set up your device with the correct permissions](https://developer.android.com/design-for-safety/privacy-sandbox/setup-device-access?version=beta)
Done
-  Make sure you are using Android UDC
I am now testing on VanillaIceCream which I believe should work.
- Make sure your version of Chrome is above 114.0.5714.0
Testing on 123.0.6312.99
- Make sure your version of WebView is above 116.0.5803.0
Testing on 123.0.6312.42
- Go to your flags on Chrome by opening chrome://flags/ and make sure the Privacy Sandbox Ads APIs experiment is enabled
Enabled
- Make sure you are in the App to Web Origin Trial by going to your [origin trials](https://developer.chrome.com/origintrials/#/trials/active) and registering for Cross App and Web Attribution Measurement Trial
Is this still required? My understanding is that as of Chrome 123 this is no longer needed.
- You can force the WebView Trial by setting flags in the [WebView Shell App](https://chromium.googlesource.com/chromium/src/+/HEAD/android_webview/docs/webview-shell.md). Go to the app, select the three dot overflow menu, select "WebView DevTools" > "Flags", then enable the flags PrivacySandboxAdsAPIsOverride and AttributionReportingCrossAppWeb
Enabled

**Comment by taddcrockett** [comment]
@samdutton @erintwalsh can we reopen this? I seem to be unable to
