### ISSUE TITLE
RFC: OpenRTB extension for passing Chrome-facilitated cookie deprecation testing labels 

### ISSUE THREAD

**Issue by dmdabbs** [privacysandbox/privacy-sandbox-dev-support#154]
We encourage the community to opt in to access the testing labels and to share the value unmodified with partners via the following OpenRTB community extension proposal.  Please take a look and discuss: 
[https://github.com/InteractiveAdvertisingBureau/openrtb/pull/143](https://github.com/InteractiveAdvertisingBureau/openrtb/pull/143).

Chrome team, many organisations implement a hard "code freeze" in Q4. Your explainer currently only offers `example_label_1` as an example. If the labels are not self-describing, we will need a real spec to completely prepare to plumb and interpret the labels. Thank you.

**Comment by dmdabbs** [comment]
Chrome team, underscoring the following closely related suggestion: https://github.com/GoogleChromeLabs/privacy-sandbox-dev-support/issues/153.

**Comment by clementsimon** [comment]
Hi @dmdabbs, closing this issue and linking to your [recommendation for passing the label in OpenRTB](https://github.com/InteractiveAdvertisingBureau/openrtb/blob/main/extensions/community_extensions/deprecation_test_label.md).
