### ISSUE TITLE
3PC deprecation timeline

### ISSUE THREAD

**Issue by AllianceDigitale** [privacysandbox/privacy-sandbox-dev-support#158]
Hi Google Chrome team,

During our recent meeting, you provided an explanation of the existing 3PC (Third-Party Cookies) depreciation timeline, which comprises the following phases:

January 2024:

- A gradual increase in Chrome traffic without 3PC, reaching 1%.
- Q1-Q2 2024: No further ramp-up is planned during this period due to ongoing market testing.
- H2 2024: The depreciation process will recommence, aiming to achieve 100% 3PC depreciation by the year's end.

As previously discussed, we wish to highlight the concerns expressed by Alliance digitale regarding the proposed depreciation in Q4 2024. These concerns are grounded in the following considerations:

- Q4 represents a significant and busy period of the year, during which many adtech companies suspend their production deployments to mitigate potential disruptions.
- The ramp-up process for publishers is expected to require a considerable amount of time, and the current timeline appears to be rather stringent.
- The market is undergoing a period of flux characterized by fluctuating budgets that may shift between the open web and other platforms, along with evolving competitive dynamics.

While we acknowledge the necessity of resuming the depreciation process after the conclusion of market testing, we would like to propose an adjustment to the plan as follows:

- Implement a complete freeze in Q4 2024.
- Gradually ramp up outside of Q4, for instance, at a rate of 1% per day.

This approach would serve to safeguard the activity of our members during the crucial year-end period, without compromising the overall completion of the 3PC depreciation plan.

Sincerely,
Alliance Digitale

**Comment by AllianceDigitale** [comment]
Hi again Google Chrome team,

Following our recent discussion, we underscored the challenges faced by a majority of our members in comprehending testing procedures and effectively conducting tests in the upcoming months.

This issue poses a significant concern for us, as the entry costs for testing the Privacy Sandbox API remain disproportionately high, particularly in the current economic climate.

Recognizing the importance of widespread industry testing to gather comprehensive feedback, we propose the following ideas:

* Develop comprehensive guidebooks detailing the implementation of Privacy Sandbox APIs for different market actors (SSP, DSP). These guidebooks would provide step-by-step instructions for stakeholders to seamlessly integrate the API.
* Create additional guidebooks focusing not only on API usage but also on the implementation of critical market use cases with various Privacy Sandbox APIs (e.g., targeting, capping, measurement). This approach would enhance market players' understanding of the Privacy Sandbox, allowing them to prioritize the use cases for testing.
* Bolster the team dedicated to supporting industry testing, with particular attention to smaller players.

Implementing this three-pronged strategy would undoubtedly facilitate the active participation of a majority of our members in testing, thereby serving the interests of both the Privacy Sandbox and the Google Chrome team.

Best regards, 

Alliance Digitale

**Comment by AllianceDigitale** [comment]
Dear Google Chrome Team,

We wish to draw your attention to our recently raised concerns, as detailed above, regarding the 3PC depreciation timeline, specifically in relation to our apprehensions about Q4 2024 and our proposal for an adjusted trajectory.

Chrome has recently revised the timeline for 3PC deprecation, now slated to commence in mid Q3 rather than early Q3. Notably, the endpoint of deprecation has been rescheduled to mid Q4 instead of the year's end.

Our heightened concerns about 3PC depreciation in Q4 have become even more pertinent due to the accelerated timeline (3 months instead of 6). Moreover, given our understanding that over half of the 3PC deprecation is now concentrated in Q4, we reiterate our plea for a complete freeze during this period, anticipating grave market disruptions.

Additionally, we advocate for greater clarity in the timeline concerning the CMA commitments and the impending standstill period, commencing at the end of Q2. 

We acknowledge the recent adjustment considers a standstill period lasting only two months, initiating 3PC depreciation in September 2024 at the earliest. Considering the CMA's authority to extend this period up to a total of 4 months, we believe displaying this information on the Google timeline would convey a necessary message of clarity and transparency.

Best regards,
Alliance Digitale

**Comment by samdutton** [comment]
Thank you for this feedback. We are aware of industry seasonal timing considerations, and acknowledge that variables like the CMA's evaluation and standstill period inform the specific timing for third-party cookie deprecation in Chrome.

We welcome suggestions regarding the [privacysandbox.com](privacysandbox.com) site and timeline visual.  However, our goal of removing third-party cookies in 2024 remains, and we want to provide clear notice to the ecosystem that this process could begin as early as Q3 2024.

Chrome has provided a considerable amount of time to help publishers, ad tech, and advertisers transition from third-party cookies:

-   [The Privacy Sandbox initiative](https://blog.google/products/chrome/building-a-more-private-web/) was announced in August 2019.
-   [The plan to phase out support for third-party cookies in Chrome](https://blog.chromium.org/2020/01/building-more-private-web-path-towards.html) was announced at the beginning of 2020.
-   [Origin trials for Privacy Sandbox APIs](https://privacysandbox.com/open-web/#the-privacy-sandbox-timeline:~:text=Privacy%20Sandbox%20APIs) began in 2021, and the Protected Audience API was made available behind a feature flag in Q2 2021.
-   [The origin trial for ad relevance and measurement APIs](https://developer.chrome.com/origintrials/#/view_trial/771241436187197441) was available from Q1 2022 through 15 versions of Chrome, to ensure adequate time for testing.

In addition, we've received feedback from the ad tech ecosystem about the importance of having a consistent timeline without unnecessary delays to allow for optimal planning by ad tech companies. We value the feedback and are doing our best to assist in such planning.

**Comment by AllianceDigitale** [comment]
Dear Google Chrome Team,

Thank you for your response and for considering our concerns regarding the third-party cookie deprecation timeline.

While we appreciate the efforts you've provided for the transition away from third-party cookies, we'd like to emphasize that our definition of a "consistent timeline without unnecessary delays" may differ. Our industry members face unique challenges, specifically during critical periods such as Q4. We understand the goal is to start the deprecation process as early as mid Q3 2024; however, we would like to stress the importance of considering a more accommodating trajectory that accounts for potential disruptions during Q4 2024.

Moreover, regarding the CMA evaluation and planned standstill period, we believe that for Google Chrome to provide clarity on the timeline, indicating a potential start in Q1 2025 rather than Q3 2024 would be a necessary step to assist in the planning efforts of the industry.

We remain committed to the successful implementation of the Privacy Sandbox initiative and appreciate our ongoing collaboration.

Best regards,
Alliance Digitale

**Comment by jonasz** [comment]
Please also see https://github.com/WICG/turtledove/issues/717#issuecomment-1847118918 for some discussion on timeline, and timeline clarity.

**Comment by samdutton** [comment]
No further follow up for more than six months, so closing this issue, but feel free to reopen if necessary.
