### ISSUE TITLE
App2Web - How to check if the source_id has been successfully registered.

### ISSUE THREAD

**Issue by Peter-WF** [privacysandbox/privacy-sandbox-dev-support#179]
Previously, I have completed the app2app and web2web tests on my device, everything went smoothly. Currently, I am testing app2web and want to know how to check if the source_id has been successfully registered.

Test process:

Step 1, use this [demo app](https://github.com/android/privacy-sandbox-samples/tree/main/AttributionReporting/MeasurementSampleApp), modify the Server Source URL(like this https://workspace-ws2b86d896b1b1435f8fea2b70205a77f6-http-8080.ide.byted.org/source) for the source_id, then click "Register Click Event"

Step 2, open the Chrome browser on my phone, request the Server Trigger URL in the browser, and register trigger_data.

Currently, through the tool (chrome://attribution-internals/), I can see a registration failed trigger_data, but cannot see the source_id.

![image](https://github.com/GoogleChromeLabs/privacy-sandbox-dev-support/assets/13869200/3a2d2f4c-0a38-4c59-afc3-22563bdff17f)

![image](https://github.com/GoogleChromeLabs/privacy-sandbox-dev-support/assets/13869200/c0e0ddf1-716e-406b-8077-6c48dbc1088b)

![image](https://github.com/GoogleChromeLabs/privacy-sandbox-dev-support/assets/13869200/5e058495-cfcc-4a0d-874e-39f100486b1f)

**Comment by samdutton** [comment]
There hasn't been any activity on this issue for several months, so I'm going to close it. Feel free to reopen if necessary.
