### ISSUE TITLE
Cross App and Web Attribution reporting - sdk implementation

### ISSUE THREAD

**Issue by roistaboola** [privacysandbox/privacy-sandbox-dev-support#183]
Hi, I've opened this case https://github.com/WICG/attribution-reporting-api/issues/1106
but was advised to open a new case at this platform.
 
 
the use case in reference has the SDK (at the publisher app) presenting the Ad and call the OS android API registerSource(register source end point url).
that request is successful as the API does send an http request to the and the register source end point.

The Ad is then presented at the Web browser on the advertiser site page where our 3p script send http impression logs.
The logs http request were added the attribution request & response headers as follows::

request headers:
Attribution-Reporting-Eligible: trigger
Attribution-Reporting-Support: os, web

response headers:
Attribution-Reporting-Support: os, web
Attribution-Reporting-Register-OS-Trigger: register trigger end point url

Though all permissions were set at the browser (Chrome Version is 119) and Privacy Sandbox Ads API was enabled and the enrollment check was skipped (chrome://flags), the browser did not send a request to the register trigger end point url.

1. what should be done for the browser to send a request to the URL defined at Attribution-Reporting-Register-OS-Trigger ?

Have also tried with Registration to an Origin Trial for the Cross App and Web Attribution Measurement trial with these values:
Third Party: Yes
Origin: the script web origin

Have added the method defined at
https://github.com/GoogleChrome/OriginTrials/blob/gh-pages/developer-guide.md#16-can-i-provide-tokens-by-running-script
to the 3p script (that send the http request with the attribution related headers).

The browser still did not send a request to the register trigger end point url.
2. is that the expected use of the Token ? can the Token be added to the header ? what should be done for the browser to send a request to the URL defined at Attribution-Reporting-Register-OS-Trigger ?

**Comment by apasel422** [comment]
@roistaboola Are you still encountering this problem?

**Comment by roistaboola** [comment]
no, issue resolved (Attribution-Reporting-Register-OS-Trigger header content fixed using the header validation tool).

**Comment by ZOONEWEIKWE** [comment]
I reset and re started my phone.it seems to be working okay
