### ISSUE TITLE
measurementManager.registerSource Invalid scheme for app destination: https; dropping the source

### ISSUE THREAD

**Issue by roistaboola** [privacysandbox/privacy-sandbox-dev-support#211]
Hi,
A register source endpoint had been defined at https://the_host_uri/endpoint_path?parameters

calling the registerSource attribution API as follows,
measurementManager.registerSource(attributionSourceUri, null, mCallback );

generated the exception:
2023-12-17 13:45:57.413 17656-17690 adservices com.google.android.adservices.api E Invalid scheme for app destination: https; dropping the source.

at times, this error is written as well:
AndroidRuntime com.google.android.adservices.api FATAL exception:
java.lang.ClassCastException: com.android.okhttp.internal.huc.HttpURLConnectionImpl cannot be cast to javax.net.ssl.HttpsURLConnection at com.android.adservices.service.measurement.MeasurementHttpClient.setup(MeasurementHttpClient.java:63) at com.android.adservices.service.measurement.registration.AsyncSourceFetcher.openUrl(AsyncSourceFetcher.java:705)

Please note:

the sdk project and taboola trc server are using javax.net.ssl.HttpsURLConnection
the request to the end point service is successful if sent from postman.
in case the endpoint service is a postman mock server, there is no error and registerSource is sent to the mock server.
I'd like to ask what is blocking the request from being sent to the actual endoint (not the mock server) and how it can be resolved.
Thanks !

**Comment by csharrison** [comment]
As far as I understand, app destinations can only be specified with the `android-app` scheme which specifies a package name. Would that be possible for your use-case?

I don't have any insight into the bad cast problem though.

cc @arpanah @vikassahu29

**Comment by vikassahu29** [comment]
Please use the `web_destination` field for specifying any websites you want use as destination. The `destination` field is used only for app destinations.

[Documentation Reference](https://developers.google.com/privacy-sandbox/relevance/attribution-reporting/android/developer-guide#accept-source-registration)

**Comment by roistaboola** [comment]
Thanks @vikassahu29, using the web_destination field did work for the app-to-web.
