### ISSUE TITLE
Size of content displayed in the fenced frame

### ISSUE THREAD

**Issue by k-o-ta** [privacysandbox/privacy-sandbox-dev-support#220]
The size of the content displayed in the fenced frame looks different between desktop and smartphone.
You can check by [protected audience demo page](https://protected-audience-demo-publisher.web.app/).

Desktop(120.0.6099.129（Official Build） （x86_64)
<img width="1160" alt="image" src="https://github.com/GoogleChromeLabs/privacy-sandbox-dev-support/assets/5237032/e7652e5e-18ad-422e-9f6b-7e3c9825b565">

Smartphone in devlopertool(120.0.6099.129（Official Build） （x86_64)
<img width="1068" alt="image" src="https://github.com/GoogleChromeLabs/privacy-sandbox-dev-support/assets/5237032/b69ca559-54e3-4495-8728-61bb49b61399">

Real Smartphone(Android 14; Pixel 7. Chrome 120.0.6099.144)
<img width="1737" alt="image" src="https://github.com/GoogleChromeLabs/privacy-sandbox-dev-support/assets/5237032/0458dc4b-e648-48c6-be0b-d6e6de47d29c">

Is this behavior intentional? I believe the behavior in Desktop is correct.

**Comment by shivanigithub** [comment]
@gtanzer Can you PTAL at this, thanks!

**Comment by gtanzer** [comment]
I think this is related to a known issue https://bugs.chromium.org/p/chromium/issues/detail?id=1317704 . Increased the issue's priority and will look into it.

**Comment by blu25** [comment]
Thanks for your patience with this. A fix is in place now. It should be working on Chrome Canary today and will make it into the 132 release in early January.

**Comment by samdutton** [comment]
I'll close this as completed, but feel free to reopen if necessary.
