### ISSUE TITLE
Clarification on Mode B and Mode A Traffic Selection and Opt-Out Prompts

### ISSUE THREAD

**Issue by ebselman** [privacysandbox/privacy-sandbox-dev-support#242]
**Context:**
To avoid selection biases in our market testing and uphold transparency, we seek clarification on the following aspects related to Mode B and Mode A traffic in Chrome:

**Questions:**

Could the Chrome team provide clarification on the methodology behind the selection of Mode B label traffic? Is it entirely random, or are there specific exclusion criteria employed to identify eligible users for the test? Furthermore, do these exclusion criteria extend to users in Mode A?

Regarding users assigned to Mode B, will they encounter any prompts allowing them to opt out of the test? If affirmative, we would like to know whether users in Mode A are subject to the same opt-out prompts.

Your insights on these matters would be greatly appreciated.

**Comment by rowan-m** [comment]
The inclusion criteria for Mode A and Mode B are the same. The aim is to have groups that are representative of normal Chrome traffic as long as they support the Privacy Sandbox APIs and the labeling method, as such some client configurations are not compatible. For the purposes of the experiment, it's important to only compare labeled traffic to other labeled traffic.

Users in Mode B have the Tracking Protection feature as detailed in https://blog.google/products/chrome/privacy-sandbox-tracking-protection/ and as such, they receive a notification about that feature.

**Comment by clementsimon** [comment]
Hey @ebselman, are you happy to close this issue?
