### ISSUE TITLE
Attribution Reporting Error on chrome

### ISSUE THREAD

**Issue by kravish1** [privacysandbox/privacy-sandbox-dev-support#243]
Hi Team,
I've successfully implemented attribution reporting by registering sources using the provided method below. However, I've encountered an issue where some user traffic triggers the following error when invoking the fetch operation:

`Failed to execute 'fetch' on 'Window': Attribution Reporting operations require that the attribution-reporting Permissions Policy feature be enabled.` The logs show that this error is widespread across various chrome versions.

Interestingly, I am unable to reproduce this issue personally. Could you shed some light on the potential causes or provide guidance on troubleshooting this matter?

Here is the code snippet used for attribution reporting:
```
// With fetch
const attributionReporting = {
  eventSourceEligible: true,
  triggerEligible: false,
};

// Optionally set keepalive to ensure the request outlives the page.
window.fetch("https://adtech.example/attribution_source?my_ad_id=123", { 
  keepalive: true, attributionReporting });
```

**Comment by kravish1** [comment]
@maybellineboon, any pointers on this?

**Comment by csharrison** [comment]
Hello, this indicates that the embedder has forbidden the API, since the API is governed by [Permissions Policy](https://developer.mozilla.org/en-US/docs/Web/HTTP/Permissions_Policy):
https://wicg.github.io/attribution-reporting-api/#permission-policy-integration

**Comment by kravish1** [comment]
@csharrison , is there a way to fix this?

**Comment by csharrison** [comment]
It will typically require changes to the top level page, which has explicitly used Permission Policy to deny access to the API. In your logs, can you break down the errors by which pages they are occuring on? If you have such a page, you might be able to reproduce and see where this is happening.

**Comment by kravish1** [comment]
@csharrison , As part of my role at LinkedIn, I've been overseeing the implementation of this particular attribution reporting feature. We've integrated this feature by utilizing our internal endpoint, https://px.ads.linkedin.com/attribution_source, which in turn interacts with the Google API.

Currently, my team and I haven't been able to reproduce the reported issue when testing in Chrome browsers. However, it's been observed that the errors are arising from user traffic accessing LinkedIn and scrolling through the feed.

We're actively investigating this discrepancy to pinpoint the source of the issue and implement a resolution. If you have any insights or suggestions regarding this matter, I'd greatly appreciate your input.

**Comment by csharrison** [comment]
Is ARA deployed on 100% of LinkedIn traffic? i.e. can we reproduce a successful registration by scrolling the feed?

**Comment by kravish1** [comment]
@csharrison , it is currently ramped to 10% of linkedin traffic and all linkedin employees and yes I am able to see a successful registration in chrome://attribution-internals/ where the sourceType is Event

**Comment by csharrison** [comment]
Hello @kravish1 . Thank you for the report. I have debugged the issue and I believe that one source of this error could be coming from ad blocking extensions like ublock origin:
https://github.com/uBlockOrigin/uAssets/blob/47ca6b8f30d6550370764bfa1cd8c0aa43d056bd/filters/privacy.txt#L581

It appears these extensions inject permissions into the page to disallow the Privacy Sandbox APIs. Please let me know if you think this could explain the problem you are having.

**Comment by kravish1** [comment]
@csharrison , I think it makes sense, let me install the ad block origin and see if I can reproduce the issue. will keep you posted

**Comment by kravish1** [comment]
@csharrison , is this specific to ublock origin or there could be other ad blockers also blocking this request?

**Comment by csharrison** [comment]
Hey @kravish1 sorry I don't know. Given that the permissions filter list rule appears to be somewhat standard (see discussion about AdGuard in https://github.com/uBlockOrigin/uBlock-issues/discussions/2714), it seems possible this could be coming from multiple ad blockers.

**Comment by clementsimon** [comment]
Hi @kravish1, bumping this one up - have you been able to reproduce the issue?

**Comment by apasel422** [comment]
@kravish1

> In light of these challenges, I'm considering whether transitioning to XMLHttpRequest might help resolve these issues.

Without seeing an example error it's hard to say for sure, but I would be surprised if any Attribution-Reporting-related error you are encountering with `fetch` wouldn't *also* happen with `XMLHttpRequest.` Attribution Reporting doesn't prefer one or the other, but in general the web has been moving away from `XMLHttpRequest` toward `fetch` for a while now, and nothing about Attribution Reporting should be moving you away from `fetch`, unless we have an unintentional bug.

Would it be possible for you to post one of these `TypeError`s here?

**Comment by kravish1** [comment]
@csharrison , yes privacy filter is enabled yet not able to reproduce locally. 
<img width="792" alt="Screenshot 2024-03-12 at 10 42 43 AM" src="https://github.com/GoogleChromeLabs/privacy-sandbox-dev-support/assets/7867801/71b1a99e-0275-406c-aa1c-7bec343387e7">

**Comment by kravish1** [comment]
> @kravish1
> 
> > In light of these challenges, I'm considering whether transitioning to XMLHttpRequest might help resolve these issues.
> 
> Without seeing an example error it's hard to say for sure, but I would be surprised if any Attribution-Reporting-related error you are encountering with `fetch` wouldn't _also_ happen with `XMLHttpRequest.` Attribution Reporting doesn't prefer one or the other, but in general the web has been moving away from `XMLHttpRequest` toward `fetch` for a while now, and nothing about Attribution Reporting should be moving you away from `fetch`, unless we have an unintentional bug.
> 
> Would it be possible for you to post one of these `TypeError`s here?

@apasel422 , the stacktrace for the typeError doesn't show much info. I've changed the code to use XMLHttpRequest, will update the behavior once my change gets deployed to prod. thanks!

**Comment by apasel422** [comment]
@kravish1

> the stacktrace for the typeError doesn't show much info. I've changed the code to use XMLHttpRequest, will update the behavior once my change gets deployed to prod. thanks!

If you provide the source code you were using with `fetch`, I may be able to debug the problem directly.

**Comment by kravish1** [comment]
> @kravish1
> 
> > the stacktrace for the typeError doesn't show much info. I've changed the code to use XMLHttpRequest, will update the behavior once my change gets deployed to prod. thanks!
> 
> If you provide the source code you were using with `fetch`, I may be able to debug the problem directly.

@apasel422 , I've changed the code to use XMLHttpRequest and below is the snapshot of the code. On checking the logs, the majority of the errors (90%) comes from the logger statement in the catch block. All the privacy policy (adblocker) related errors gets captured in the status === 0 condition inside onreadystatechange callback.

  ```
  if (attributionUrl) {
      const attributionReporting = {
        eventSourceEligible: true,
        triggerEligible: false,
      };
      try {
        if (isUrl(attributionUrl) && IS_BROWSER) {
          const req = new window.XMLHttpRequest('GET', attributionUrl);
          req.open('GET', attributionUrl);
          if (!Ember.testing) {
            req.setAttributionReporting(attributionReporting);
          }
          req.onreadystatechange = () => {
            if (req.readyState === 4) {
              const { status } = req;
              if (status === 200) {
                incrementMetricCounter(
                  clientSensor,
                  SponsoredTrackingClientSensorMetrics.ARA_ENDPOINT_INVOKE_SUCCESS
                );
              } else {
                incrementMetricCounter(
                  clientSensor,
                  SponsoredTrackingClientSensorMetrics.ARA_ENDPOINT_INVOKE_FAILURE
                );
                const xhrError = `${status} : ${attributionUrl}`;
                if (status === 0) {
                  // Handle status 0 error
                  logError(
                    jet,
                    `${xhrError} : XHR request failed: Status 0 - Network error or policy violation`,
                    'Error invoking XHR Request status 0'
                  );
                } else if (status !== 200) {
                  // Handle non-200 status error
                  logError(
                    jet,
                    `${xhrError} : XHR request failed: non-200 status code`,
                    'Error invoking XHR Request status non-200'
                  );
                }
              }
            }
          };
          req.send();
        } else {
          logError(
            jet,
            `Invalid attribution URL ${attributionUrl}`,
            'Invalid attribution URL'
          );
        }
      } catch (error) {
        incrementMetricCounter(
          clientSensor,
          SponsoredTrackingClientSensorMetrics.ARA_ENDPOINT_INVOKE_FAILURE
        );
        logError(
          jet,
          `Failed to call XMLHttpRequest ${attributionUrl}`,
          'Error fetching attribution URL:'
        );
        throw error;
      }
    } 
```

**Comment by apasel422** [comment]
@kravish1 Are you sure that your JavaScript code is always executing in a secure context? If not, then the `setAttributionReporting` method won't be available on `XMLHttpRequest`, which would manifest as something like `Uncaught TypeError: req.setAttributionReporting is not a function.`

To help narrow this down, I'd suggest explicitly [checking the feature policy](https://developers.google.com/privacy-sandbox/relevance/attribution-reporting/getting-started#dont_forget_feature_detection) *and* availability of the method before calling it:

```js
const req = new window.XMLHttpRequest('GET', attributionUrl);
req.open('GET', attributionUrl);
if ('setAttributionReporting' in req) {
  req.setAttributionReporting(...);
} else {
  logError(...);
}
```

**Comment by kravish1** [comment]
> checking the feature policy

@apasel422 , interesting. I am currently using `'featurePolicy' in document` for registering the click sources, I can try adding the check you suggested for view conversion as well. In the doc you pinged, it says **Note that this check alone isn't a guarantee that the API is usable on that page; the user may have disabled the API via their browser settings, or they may have other settings that prevent the API from being used. In order to protect user privacy, there is no way to check for this programmatically.** So there are bound to be failures that we won't have control of?

**Comment by apasel422** [comment]
> So there are bound to be failures that we won't have control of?

Yes, there are a variety of reasons that the API doesn't end up actually being enabled, though I don't think those would result in a `TypeError`.

**Comment by kravish1** [comment]
> > So there are bound to be failures that we won't have control of?
> 
> Yes, there are a variety of reasons that the API doesn't end up actually being enabled, though I don't think those would result in a `TypeError`.

@apasel422 , you are correct. I see the same error in the stacktrace 
t.setAttributionReporting is not a function

`setAttributionReporting() at e.fetchAndInvokeARAEndpoint (https://static.licdn.com/aero-v1/sc/h/2wfhjenix9yqwnybiyl37wvte:27363:22)`

Will adding the featurePolicy check resolve this issue? Also just curious, most of the typeErrors recorded are from the chrome browser, isn't this enabled by default in chrome?

**Comment by apasel422** [comment]
> Will adding the featurePolicy check resolve this issue? Also just curious, most of the typeErrors recorded are from the chrome browser, isn't this enabled by default in chrome?

No, the feature-policy check alone wouldn't prevent this ([and it is indeed enabled by default](https://wicg.github.io/attribution-reporting-api/#permission-policy-integration)).

Per [my previous comment](https://github.com/GoogleChromeLabs/privacy-sandbox-dev-support/issues/243#issuecomment-1999581068), I suspect that the issue is that your code is being invoked from an insecure context, which would manifest as the `setAttributionReporting` method being absent.

**Comment by kravish1** [comment]
> > Will adding the featurePolicy check resolve this issue? Also just curious, most of the typeErrors recorded are from the chrome browser, isn't this enabled by default in chrome?
> 
> No, the feature-policy check alone wouldn't prevent this ([and it is indeed enabled by default](https://wicg.github.io/attribution-reporting-api/#permission-policy-integration)).
> 
> Per [my previous comment](https://github.com/GoogleChromeLabs/privacy-sandbox-dev-support/issues/243#issuecomment-1999581068), I suspect that the issue is that your code is being invoked from an insecure context, which would manifest as the `setAttributionReporting` method being absent.

@apasel422 , I am explicitly checking if the content is **browser** in the calling function.

**Comment by apasel422** [comment]
> I am explicitly checking if the content is **browser** in the calling function.

Sorry, could you clarify what you mean by "the content is browser"? Attribution Reporting functionality is only available in JavaScript when the [context is secure](https://www.w3.org/TR/secure-contexts/#intro), typically meaning that the page is using HTTPS (not HTTP).

**Comment by kravish1** [comment]
> JavaScript code is always executing in a secure context

sorry i meant context. I am using the below code to determine if the execution happens in a browser environment.
```
const IS_BROWSER =
  typeof window !== 'undefined' &&
  window &&
  (window as CustomWindow).appEnvironment !== 'node';
```

**Comment by apasel422** [comment]
> sorry i meant context. I am using the below code to determine if the execution happens in a browser environment.

I see. Unfortunately that is orthogonal to whether the context is secure. Is it possible that your code is running on a page that is accessed over `http://` instead of `https://`? That would be my prime suspect for the issue you are encountering.

**Comment by kravish1** [comment]
> https://px.ads.linkedin.com/attribution_source?impression_id=f8a9548f-455d-4fdf-b7da-23d4d703706d&destination=https://www.google.com'

So this is the sample endpoint that gets invoked as part of the XMLHttpRequest.
`https://px.ads.linkedin.com/attribution_source?impression_id=f8a9548f-455d-4fdf-b7da-23d4d703706d&destination=https://www.google.com'`

`https://px.ads.linkedin.com/attribution_source` is our backend api endpoint. Is there something more specific that I can add to make sure the context is secure?

**Comment by apasel422** [comment]
> Is there something more specific that I can add to make sure the context is secure?

We need to know the URL of the page(s) that ultimately call the `XMLHttpRequest.setAttributionReporting` method, not the URL of the endpoint that is *being* fetched.

For example, if there's a page like `http://a.example` that runs your code, perhaps by embedding an iframe, the call will fail, because that page is not secure.

**Comment by apasel422** [comment]
(And by the way, totally separate from the issue this thread is about, the JSON coming from the endpoint you provided [is not valid](https://wicg.github.io/attribution-reporting-api/validate-headers?header=source&json=%7B%22source_event_id%22%3A%2213247940650911101037%22%2C%22debug_key%22%3A%2217917945566791028703%22%2C%22destination%22%3A%22https%3A%2F%2Fgoogle.com%22%2C%22expiry%22%3A%222592000%22%2C%22priority%22%3A%220%22%2C%22filter_data%22%3A%7B%22c%22%3A%5Bnull%5D%7D%7D&source-type=event&flex=false) for registering a source because it erroneously contains `null` in its `filter_data`.)

**Comment by kravish1** [comment]
> https://px.ads.linkedin.com/attribution_source

@apasel422 , understood lemme check this and get back toy you.

**Comment by kravish1** [comment]
> (And by the way, totally separate from the issue this thread is about, the JSON coming from the endpoint you provided [is not valid](https://wicg.github.io/attribution-reporting-api/validate-headers?header=source&json=%7B%22source_event_id%22%3A%2213247940650911101037%22%2C%22debug_key%22%3A%2217917945566791028703%22%2C%22destination%22%3A%22https%3A%2F%2Fgoogle.com%22%2C%22expiry%22%3A%222592000%22%2C%22priority%22%3A%220%22%2C%22filter_data%22%3A%7B%22c%22%3A%5Bnull%5D%7D%7D&source-type=event&flex=false) for registering a source because it erroneously contains `null` in its `filter_data`.)

oh, thanks for pointing it out, I ll check this with the backend team.

**Comment by dmdabbs** [comment]
You can validate your response headers with the project's nifty Validator:

https://wicg.github.io/attribution-reporting-api/validate-headers

**Comment by kravish1** [comment]
> > Is there something more specific that I can add to make sure the context is secure?
> 
> We need to know the URL of the page(s) that ultimately call the `XMLHttpRequest.setAttributionReporting` method, not the URL of the endpoint that is _being_ fetched.
> 
> For example, if there's a page like `http://a.example` that runs your code, perhaps by embedding an iframe, the call will fail, because that page is not secure.

@apasel422 , not sure if I understood the page example. My code (invoking the px.ads endpoint mentioned above ) when the user launches linkedin.com (which is secure) and scrolls through the feed.

**Comment by apasel422** [comment]
> not sure if I understood the page example. My code (invoking the px.ads endpoint mentioned above ) executes when the user launches linkedin.com (which is secure) and scrolls through the feed and when the ad is in the user's viewport.

Could you provide the URL of a page that has exhibited the `TypeError` so that I can try this myself?

**Comment by kravish1** [comment]
> > not sure if I understood the page example. My code (invoking the px.ads endpoint mentioned above ) executes when the user launches linkedin.com (which is secure) and scrolls through the feed and when the ad is in the user's viewport.
> 
> Could you provide the URL of a page that has exhibited the `TypeError` so that I can try this myself?

@apasel422 , you can go to linkedin home page https://www.linkedin.com/feed/. Start scrolling through your feed and for every 3rd post which is sponsored which comes into your viewport, you'll see this url invoked https://px.ads.linkedin.com/attribution_source. This feature is open to only 10% of the traffic so there is a chance that this might not be enabled for you. Also and the error does not occur for everyone but you can try it and let me know.

![Screenshot 2024-03-16 at 6 58 22 PM](https://github.com/GoogleChromeLabs/privacy-sandbox-dev-support/assets/7867801/c79d1dfc-dd05-4337-8c1d-be49ca7dad4b)

**Comment by apasel422** [comment]
> This feature is open to only 10% of the traffic so there is a chance that this might not be enabled for you.

Unfortunately, I'm not seeing any requests to https://px.ads.linkedin.com/attribution_source.

**Comment by kravish1** [comment]
> > This feature is open to only 10% of the traffic so there is a chance that this might not be enabled for you.
> 
> Unfortunately, I'm not seeing any requests to https://px.ads.linkedin.com/attribution_source.

@apasel422 , lemme try to enable this feature for your linkedin profile. will let you know once thats done.

**Comment by kravish1** [comment]
> > > This feature is open to only 10% of the traffic so there is a chance that this might not be enabled for you.
> > 
> > 
> > Unfortunately, I'm not seeing any requests to https://px.ads.linkedin.com/attribution_source.
> 
> @apasel422 , lemme try to enable this feature for your linkedin profile. will let you know once thats done.

@apasel422 , I've activated this feature for you, can you try now?

**Comment by apasel422** [comment]
> I've activated this feature for you, can you try now?

I'm still not seeing any requests to https://px.ads.linkedin.com/attribution_source.

**Comment by kravish1** [comment]
> > I've activated this feature for you, can you try now?
> 
> I'm still not seeing any requests to https://px.ads.linkedin.com/attribution_source.

It should show up, try scrolling through your feed on desktop and the request should show for most the the sponsored posts. This is your linkedin profile right? https://www.linkedin.com/in/andrew-paseltiner-ba07912ba/

**Comment by apasel422** [comment]
> This is your linkedin profile right?

Yes. But I'm still not seeing any relevant requests, unfortunately.

Is it possible for you to feature-detect using both the feature-policy check and `typeof XMLHttpRequest.prototype.setAttributionReporting === 'function'? I'm not sure what other errors related to Attribution Reporting could be occurring if both of these checks are in place.

**Comment by kravish1** [comment]
> > This is your linkedin profile right?
> 
> Yes. But I'm still not seeing any relevant requests, unfortunately.
> 
> Is it possible for you to feature-detect using both the feature-policy check and `typeof XMLHttpRequest.prototype.setAttributionReporting === 'function'`? I'm not sure what other errors related to Attribution Reporting could be occurring if both of these checks are in place.

alright, maybe it is taking a while to show up. But yes, lemme try to add these 2 checks in place and observe the logs. Will keep you posted. Thanks for all the support so far!

**Comment by miketaylr** [comment]
Feel free to add https://www.linkedin.com/in/mike-taylor-7a09163/ to this experiment as well (I checked, and seem to not be in the 10% bucket).

**Comment by kravish1** [comment]
> > This is your linkedin profile right?
> 
> Yes. But I'm still not seeing any relevant requests, unfortunately.
> 
> Is it possible for you to feature-detect using both the feature-policy check and `typeof XMLHttpRequest.prototype.setAttributionReporting === 'function'`? I'm not sure what other errors related to Attribution Reporting could be occurring if both of these checks are in place.

@apasel422 , with this check `typeof XMLHttpRequest.prototype.setAttributionReporting === 'function'` in place, the typeError is now resolved. However if we are to switch back to using the fetch call instead of the XmlHttpRequest, does the same check suffice or should this be different for fetch?

**Comment by apasel422** [comment]
> f we are to switch back to using the fetch call instead of the XmlHttpRequest, does the same check suffice or should this be different for fetch?

The exact same check would suffice. (There is no `setAttributionReporting` *method* for `fetch`, but that method is exposed on `XMLHttpRequest` in exactly the same circumstances in which `fetch` supports the `attributionReporting` options field.

**Comment by kravish1** [comment]
> > f we are to switch back to using the fetch call instead of the XmlHttpRequest, does the same check suffice or should this be different for fetch?
> 
> The exact same check would suffice. (There is no `setAttributionReporting` _method_ for `fetch`, but that method is exposed on `XMLHttpRequest` in exactly the same circumstances in which `fetch` supports the `attributionReporting` options field.)

@apasel422 , sounds good. I ll go ahead and close this ticket. Thanks for helping with this!
