### ISSUE TITLE
Question about `destination` URL for reporting attribution source

### ISSUE THREAD

**Issue by tomhnzhou** [privacysandbox/privacy-sandbox-dev-support#267]
As an ad tech, we need to register the advertiser site URL as the `destination` URL in the `Attribution-Reporting-Register-Source ` header, as specified in the steps here: https://developers.google.com/privacy-sandbox/relevance/attribution-reporting/register-attribution-source#step_2_respond_with_header_clicks_and_views

However, one potential issue we face is: the advertiser site URL might be a redirect URL (i.e. user will be redirected to a different URL or domain). In that case, do we need to resolve the final destination URL ourselves and use that as destination? Or do you have another suggestion on how to handle redirect URLs? Thank you!

**Comment by akashnadan** [comment]
You could do either of the following:
* Put the final destination URL in the `destination` field
* The `destination` field allows up to 3 URLs, so you could put multiple URLs in that field (i.e. the initial advertiser site URL and the final URL)
