### ISSUE TITLE
Unable to register a service worker of third party from a first party

### ISSUE THREAD

**Issue by Akshay20240305** [privacysandbox/privacy-sandbox-dev-support#271]
We have a first party site (https://company.net) and it has an embedded iFrame which points to a third party site (https://scpo-app.com/scpo) both are owned by us but deployed on different domains.

We have enabled SSO on first party site and using the service worker (which is hosted on https://scpo-app.com/scpo/ui/v1/by-service-worker.js), we are authorizing 3rd party calls by intercepting and attaching an authorization token in the HTTP header for 3rd party service calls.
This implementation works seamlessly if we allow the Third-party cookie (chrome://settings/cookies?search=Third-party).

If we disable the Third-party cookie (chrome://settings/cookies?search=Third-party) and try to launch the 1st party site and access the 3rd party resource then service-worker registration fails with the following error - "Service worker registration failed  DOMException: Failed to register a ServiceWorker for scope ('https://scpo-app.com/scpo/ui/v1') with script ('https://scpo-app.com/scpo/ui/v1/by-service-worker.js'): The user denied permission to use Service Worker"

**Comment by wanderview** [comment]
What version of chrome are you testing in?

**Comment by Akshay20240305** [comment]
Hi @wanderview,

   I am using 122.0.6261.58 (Official Build) (64-bit) version of chrome.

**Comment by sbingler** [comment]
Hi @Akshay20240305,

We're unable to reproduce your problem using a test site. 

Can you please disable third-party cookies and then visit https://x-origin-src.glitch.me/tmp.html and let us know if you continue to see the "Failed to register a ServiceWorker" error? If the SW is successfully registered you'll also see a message within the iframe that says "Ready to use Offline". (Note that the message disappears after a little while and you'll have to clear the site's data if you want to see the message again). 

If the service worker is registered successfully on the test site but your site continues to fail then that may mean that your Chrome instance has enterprise policies that are affecting service workers. 

If you visit chrome://policy/ do you see either of your URLs in any of the policy values? "CookiesBlockedForUrls" is a particularly interesting one to look for.

**Comment by Akshay20240305** [comment]
Hi @sbingler,

 I am able to replicate the same problem with the following test site as well **https://x-origin-src.glitch.me/tmp.html** 

Please find the below attached screenshot for reference
<img width="959" alt="image" src="https://github.com/GoogleChromeLabs/privacy-sandbox-dev-support/assets/162281612/e72ae529-899b-40f6-a919-ac4909c33d40">

**Comment by Akshay20240305** [comment]
> @Akshay20240305 have you tested in a new profile or different Chrome instance, not just in incognito?
[Akshay20240305]: I have tried in a different chrome instance and the behavior is same, please find the below screenshot:
<img width="960" alt="image" src="https://github.com/GoogleChromeLabs/privacy-sandbox-dev-support/assets/162281612/93b0c39b-e800-4ad2-9ab2-b219b4d441ce">

> 
> > If you visit chrome://policy/ do you see either of your URLs in any of the policy values? "CookiesBlockedForUrls" is a particularly interesting one to look for.
> [Akshay20240305]: I have reviewed the policies and I don't see any mappings defined for my URL 
> Please answer this question as well.

**Comment by Akshay20240305** [comment]
One more update: My chrome browser version got updated from 122.0.6261.58 (Official Build) (64-bit) to  Version 122.0.6261.112 (Official Build) (64-bit)

**Comment by Akshay20240305** [comment]
Hi @miketaylr,
   
   I have tried the same steps from different machine's(VM) chrome browser (Version 122.0.6261.112 (Official Build) (64-bit)) which has same level of chrome policies and there the issue is not replicable. 

![image](https://github.com/GoogleChromeLabs/privacy-sandbox-dev-support/assets/162281612/0178d366-b401-4bf5-ad55-ed96b8094c45)

Could you please help me in understanding the inconsistency in the behavior?

**Comment by miketaylr** [comment]
> Could you please help me in understanding the inconsistency in the behavior?

Without having access to the policies that may be active for your machine, it's really hard to say. If you're comfortable sharing the output of the Chrome Policies section of chrome://policy (and only that section - no other info needed), you could email that to `miketaylr@google.com`. But I understand that it may not be sharable. 

Do any of your co-workers run into this issue, or are you the only one?

**Comment by Akshay20240305** [comment]
> > Could you please help me in understanding the inconsistency in the behavior?
> 
> Without having access to the policies that may be active for your machine, it's really hard to say. If you're comfortable sharing the output of the Chrome Policies section of chrome://policy (and only that section - no other info needed), you could email that to `miketaylr@google.com`. But I understand that it may not be sharable.
> [Akshay20240305]: I have sent an email with the details for your review.
> Do any of your co-workers run into this issue, or are you the only one?
 [Akshay20240305]: The issue is consistently(100%) replicable in 121.*.*.* version of browser and with the recent chrome browser (**122.0.6261.129**) upgrade, 90% of my co-workers are not experiencing this issue. For the remaining 10% of co-workers (plus me) the issue is 100% replicable.

**Comment by Akshay20240305** [comment]
Hi @miketaylr,

   We are actually assessing the impact on our application because of 3PC cookie phaseout.  

   Flag details: chrome://flags/#test-third-party-cookie-phaseout.

**Comment by Akshay20240305** [comment]
> @Akshay20240305 thanks for sending the policies - I can confirm there's nothing relevant there.
> 
> One more question: can you tell me what is the value for chrome://flags/#third-party-storage-partitioning? It should be "Default", but if you've set it to "Disabled", then what you are seeing is expected behavior.

Yes @miketaylr  that was the problem, after chaging the flag value to default or enable, issue is resolved. Thank you so much for a quick help on this matter.

**Comment by miketaylr** [comment]
Glad to hear it!
