### ISSUE TITLE
Programmatic way to know if 3p cookies are blocked

### ISSUE THREAD

**Issue by soniagupt** [privacysandbox/privacy-sandbox-dev-support#276]
Suppose site A makes ajax call to site B. Is there a programmatic way for site A to know if 3p cookies for site B are blocked for interaction between site A and site B?

#### Context:

We have a scenario similar to scenario A [mentioned here](https://developers.google.com/privacy-sandbox/3pcd/temporary-exceptions/heuristics-based-exceptions#scenario_a_-_third_party_cookie_access_after_pop-up_interaction). We want to use popup heuristics. However, we want to show user interaction once in 30 days to smoothen the customer journey.

Is there a programmatic way to know the 3p cookies are blocked ?
or a  programmatic way to know if the popup heuristic is active?

**Comment by johannhof** [comment]
For iframes, while I'm not sure there's a good way to do this across browsers, in Chrome both `navigator.cookieEnabled` and `document.hasStorageAccess` called in an iframe should let you know whether the origin in the iframe has access to third-party cookies.

Now, it sounds like you may want to do this in a pop-up, e.g. before showing a button forcing user interaction to trigger the heuristics. I don't think there's a built-in way to do this in the browser, but you could just set a first-party cookie that expires after, say, 30 days and show the button only when that cookie is not present.

Does that help?

**Comment by soniagupt** [comment]
Thanks for answering this @johannhof 

Is it possible for chrome to expose the 30 day duration as a public property/method?
asking this to avoid hardcoding this on our side in case chrome changes that in future.

**Comment by johannhof** [comment]
You could file a feature request on https://github.com/amaliev/3pcd-exemption-heuristics/issues and see if it gains traction with other developers, but I will say that given that this is a (longer-lived) temporary exception I'm not too keen on establishing it further with a dedicated web API.

**Comment by samdutton** [comment]
No further comments for >9 months, so I'll close this.
