### ISSUE TITLE
Affect of 3rd party cookie deprecation over SAML protocol

### ISSUE THREAD

**Issue by assafgrim** [privacysandbox/privacy-sandbox-dev-support#281]
Using SAML protocol, most of the authentication providers (IDP) are using a HTTP POST request from the UI (=Frontend, Javascript) to authenticate users and get a cookie in return from a server.
It means that a site (A.com) will do a POST request to as server over a different domain (B.com) and get Set-Cookie header as a result of successful authentication.
I wonder if that cookie is considered 3rd party cookie, which will harm the current SAML authentication flow?

**Comment by johannhof** [comment]
If that request is made as a top-level navigation it is not considered a third-party cookie for the purpose of 3PCD, but if the request is made in an embedded context (e.g example-ui.com makes an XHR/fetch request to example-idp.com), then those cookies would be considered third-party and blocked.

Does that make sense? You can also just test it on your own site, see https://developers.google.com/privacy-sandbox/3pcd/prepare/test-for-breakage

**Comment by assafgrim** [comment]
@johannhof it is not a top level navigation, as I said, it is a POST request made from a top-level domain (A.com) to a different domain (B.com). No iframe involved. Just a cross domain HTTP POST request, initiated intentionally by A.com, where B.com respond with Set-Cookie header. Is that consider 3rd party cookie?

**Comment by johannhof** [comment]
Yes, that is generally considered a 3rd party cookie, assuming a.com and b.com are [cross-site](https://web.dev/articles/same-site-same-origin).

**Comment by samdutton** [comment]
I'm closing this issue as there hasn't been any activity for more than two weeks, but reopen it if necessary.
