### ISSUE TITLE
Site A embeds Site B embeds Site A

### ISSUE THREAD

**Issue by bretticus-mc** [privacysandbox/privacy-sandbox-dev-support#283]
We have an iframe on Site A that embeds Site B, which embeds Site A. 

Site A also has an iframe that embeds Site A. 

The two embedded Site A’s each start a SharedWorker. 

I’m seeing in my configuration this is creating two separate SharedWorkers on Site A. Should they not use the same SharedWorker because both iframes share the same TLD+1?

I’m also seeing that the Site A iframe embedded in Site B doesn’t get access to the top-level Site A’s unpartitioned cookies. Shouldn’t the Site A iframe inherit the top-level’s cookies since they would be first-party cookies? This currently works with a Partitioned Cookie but I see this functionality is going away with the addition of an [Ancestor Chain Bit](https://groups.google.com/a/chromium.org/g/blink-dev/c/d3kJtNXcECk/m/yl4MOLLLAAAJ).

**Comment by johannhof** [comment]
@arichiv I think [non-cookie storage for Storage Access API](https://github.com/privacycg/saa-non-cookie-storage) solves this, right? And for ABA it will just auto-grant. Using SAA would also be a way to get your cross-site cookies back, although we're thinking about re-allowing this when the inner A requests are CORS-enabled, also described in https://github.com/explainers-by-googlers/standardizing-cross-site-cookie-semantics/issues/9, cc @dcthetall

**Comment by wanderview** [comment]
As I understand it, for these two scenarios:

 1. A1->B->A2
 2. A3->A4

A2 will have partitioned storage separate from A4 due to the ancestor chain bit in the first scenario.

**Comment by bretticus-mc** [comment]
Ok. Just to clarify, It's
Iframe 1: A1 -> B -> A2
Iframe 2: A1 -> A3

Both iframes are on the same site. But A2 being embedded in B is enough to cause a separate storage partition. 

Is non-cookie storage for the Storage Access API going to be implemented in Chrome? I'll be able to call document.requestStorageAccess({all: true}); and it will grant A2 access to the SharedWorker in A3?

**Comment by wanderview** [comment]
> Is non-cookie storage for the Storage Access API going to be implemented in Chrome?

This is available in an origin trial now.  It looks like SharedWorker support was added in M123:

https://developers.google.com/privacy-sandbox/blog/saa-non-cookie-storage

**Comment by arichiv** [comment]
The intent is to ship the API in Chrome 125
