### ISSUE TITLE
Topics Api resolved to UUID instead of topic

### ISSUE THREAD

**Issue by patricio-navarro** [privacysandbox/privacy-sandbox-dev-support#294]
I am not sure if this is a duplicate, as already exists an issue (https://github.com/privacysandbox/privacy-sandbox-dev-support/issues/258) but it was closed without any clarification. 

We are an ad server company. And we have the following js code:
```
getBrowsingTopics(): Observable<unknown> {
        try {
            return from((document as any).browsingTopics())
        } catch (error) {
            console.log(error)
            return of([]);
        }
    }
```

Which is loaded inside the ad iframe. The results are added to an analytics JSON message which is sent back to us. After 
 After a couple of days running this, we started to get topics from our impressions, but instead of a JSON we found these uuids.

<img width="172" alt="image" src="https://github.com/privacysandbox/privacy-sandbox-dev-support/assets/47215869/21ec57f7-8964-4e7c-9551-552ce4c37f74">

**Comment by miketaylr** [comment]
Given that https://github.com/privacysandbox/privacy-sandbox-dev-support/issues/258 has been re-opened, let's close this as a dupe and focus conversation there. Thanks!
