### ISSUE TITLE
_GRECAPTCHA cookie blocked with third-party cookie phase out

### ISSUE THREAD

**Issue by tiffsaw** [privacysandbox/privacy-sandbox-dev-support#296]
Hi,

I am wondering if Google reCaptcha v2 will work once third-party cookies are blocked? When testing it, I am seeing the  _GRECAPTCHA cookie being blocked but I'm not sure on how to proceed and if that cookie will get blocked Google starts disallowing third-party cookies. example url: https://app.mural.co/signup where Google re-captcha V2 is being used.

**Comment by krgovind** [comment]
Hi @tiffsaw - Please see the response from the Google reCAPTCHA team [here](https://github.com/privacysandbox/privacy-sandbox-dev-support/issues/228).
