### ISSUE TITLE
when the chrome version is 102,  i set cookie like this :top=xxx Path=/; Domain=ss.com; Secure; SameSite=None; Partitioned, set failed

### ISSUE THREAD

**Issue by xiaotaohong66** [privacysandbox/privacy-sandbox-dev-support#297]
Read https://developer.chrome.com/docs/privacy-sandbox/third-party-cookie-phase-out/ for context before raising issues here.

For site-specific issues with third-party cookies, please report this via https://goo.gle/report-3pc-broken

**Comment by miketaylr** [comment]
Could you please provide steps to reproduce, as well as expected and actual behavior?

**Comment by shuranhuang** [comment]
If I am understanding the issue from the tittle correctly, the problem likely comes from the `Partitioned` attribute. It [requires](https://developer.mozilla.org/en-US/docs/Web/Privacy/Privacy_sandbox/Partitioned_cookies#browser_compatibility) Chrome 114 or later.

**Comment by samdutton** [comment]
No reply in >4 months so I'll close this issue, but feel free to reopen if necessary.
