### ISSUE TITLE
Request for more aggressive ramp up and test coverage on domains opted into the 3pc third-party deprecation trial

### ISSUE THREAD

**Issue by ChasePattersonRaleigh** [privacysandbox/privacy-sandbox-dev-support#301]
Per Google’s doc [here](https://developers.google.com/privacy-sandbox/3pcd), during most of 2024, only 1% of chrome clients will have third party cookies blocked by default, then sometime after Q3 and end of the year, it will ramp up to 100% very quickly. This is a risk for our project’s rollout as it will mean certain areas may not get adequate test coverage prior to the expiration of the third party cookie deprecation trial, which is currently set at Dec 27, 2024. If issues are detected late in the year due to this, other teams and our customers might not have the time needed to respond and make appropriate adoptions. They might end up blocked once the token expires during the holiday period.

**This is more concerning to our project for a few reasons:**
1. One area we observed as needing many changes/adoptions was in our Setup UI. Only admins access this UI, which is a very small percentage of users already. Some of the functionality in this area may not be used frequently but can be crucial to business when the need for it arises. Let’s assume less than 10% of users have access to this UI for example. This limits testing already.
2. We typically rollout changes slowly into select customer sandbox environments first, then start in customer production environments later - there’s about 13 steps for our rollout here. For this project, we are using [third party cookie deprecation trial tokens](https://developers.google.com/privacy-sandbox/3pcd/temporary-exceptions/third-party-deprecation-trial) and gradually removing the tokens to roll out blocking of cookies slowly in sandbox environments first. Even though we are removing the tokens from certain test or customer sandbox environments, still only 1% of the users are going to be opted-in to the new behavior by default which means we aren’t getting a typical or large sample size for our test coverage prior to moving to production enablement. Normally we like to have full control of the rollout and enablement of new changes or features, but the 1% rule is limiting our ability to do a gradual rollout and pushing the broader testing to the last minute when things can become more disruptive if the token is about to expire when potential issues are found. By that point, we may not have a killswitch to disable the changed behavior for long and business could be blocked.

Is there a way we could have the ability to enable these changes more aggressively in general or at least for the domains in which we requested the third party cookie deprecation trial tokens so we can have better confidence at each phase of our rollout? 

We are investigating ways to mitigate this and force the cookies to get blocked by default, but this is more for whether Google is providing a more general way to ramp up sooner by default. 

Thank you

**Comment by samdutton** [comment]
Hi @ChasePattersonRaleigh 

This comment was noted at the time — apologies for the lack of reply. 

Please see [A new path for Privacy Sandbox on the web](https://privacysandbox.com/news/privacy-sandbox-update/) for an update on Chrome's plans.

I'll close this for now, but feel free to reopen if you want.
