### ISSUE TITLE
information about third-party cookies set by .google.com, .facebook.com, .youtube.com for a website

### ISSUE THREAD

**Issue by yibrino** [privacysandbox/privacy-sandbox-dev-support#308]
I recently conducted a thorough examination of our site's functionality with third-party cookies disabled, keen to identify any potential site breakage. Impressively, the site maintained its functionality seamlessly across all pages, even in the absence of third-party cookies. However, during this review, I noticed numerous cookies set by major entities such as Google.com, Facebook.com, and YouTube.com. Despite the operational integrity of the site, it's clear that data collection processes will be significantly impacted under these conditions. Given this scenario, what viable alternative solutions can we explore to address such issues? here is the website https://solutionservicescorp.com/ Please, could you provide some insight into this?

**Comment by samdutton** [comment]
Hi @yibrino — thanks for the question.

Products such as YouTube are aware of the changes, and will be making updates to ensure a smooth transition away from third-party cookies. 

• For Google Analytics, see https://github.com/privacysandbox/privacy-sandbox-dev-support/discussions/173#discussioncomment-7393749

• For Google reCAPTCHA, see https://github.com/privacysandbox/privacy-sandbox-dev-support/issues/228#issuecomment-1885828939

For other products, you'll need to contact the service provider.

**Comment by samdutton** [comment]
No follow-up for a few months, so I'm going to close this issue, but feel free to reopen if necessary.
