### ISSUE TITLE
--test-third-party-cookie-phaseout is not working when set as an argument to chromeOption while running selenium test

### ISSUE THREAD

**Issue by divya-suseelan** [privacysandbox/privacy-sandbox-dev-support#322]
Hi Team,

We are trying to run selenium test on chromeDriver version 12 by adding the below option
options.addArguments("--test-third-party-cookie-phaseout");

This argument is not reflected while executing the test and in chrome flag page we could still see Test third party cookie phaseout option as disabled.

Could you please help.

**Comment by miketaylr** [comment]
Could you clarify what version of ChromeDriver you're using? Version 12 would be very, very old.

It's possible you'll need to use Chrome for Testing instead, see https://chromedriver.chromium.org/downloads/version-selection.

**Comment by divya-suseelan** [comment]
Hi Team, it was a typo. I'm using chrome version 122. I could add the flag now via command line using chromeOptions.addArguments("--test-third-party-cookie-phaseout");

I can see the message showing third part cookie enabled, however If I go to 'chrome://flags' page it is showing as disabled

![image](https://github.com/privacysandbox/privacy-sandbox-dev-support/assets/36363467/5e2a2cc2-7143-4843-a166-3f82d5d13cfc)

**Comment by shuranhuang** [comment]
According to https://developers.google.com/privacy-sandbox/3pcd/prepare/test-for-breakage#chrome_flags_for_testing_different_scenarios,  this is because "... flags set from the command line are not reflected by the settings displayed on the chrome://flags page."

**Comment by samdutton** [comment]
Closing, but feel free to reopen.
