### ISSUE TITLE
WebView Attribution Reporting API not sending support header

### ISSUE THREAD

**Issue by taddcrockett** [privacysandbox/privacy-sandbox-dev-support#335]
@erintwalsh still no luck. 

- Follow all instructions to [set up your device with the correct permissions](https://developer.android.com/design-for-safety/privacy-sandbox/setup-device-access?version=beta)
Done
-  Make sure you are using Android UDC
I am now testing on VanillaIceCream which I believe should work.
- Make sure your version of Chrome is above 114.0.5714.0
Testing on 123.0.6312.99
- Make sure your version of WebView is above 116.0.5803.0
Testing on 123.0.6312.42
- Go to your flags on Chrome by opening chrome://flags/ and make sure the Privacy Sandbox Ads APIs experiment is enabled
Enabled
- Make sure you are in the App to Web Origin Trial by going to your [origin trials](https://developer.chrome.com/origintrials/#/trials/active) and registering for Cross App and Web Attribution Measurement Trial
Is this still required? My understanding is that as of Chrome 123 this is no longer needed.
- You can force the WebView Trial by setting flags in the [WebView Shell App](https://chromium.googlesource.com/chromium/src/+/HEAD/android_webview/docs/webview-shell.md). Go to the app, select the three dot overflow menu, select "WebView DevTools" > "Flags", then enable the flags PrivacySandboxAdsAPIsOverride and AttributionReportingCrossAppWeb
Enabled

_Originally posted by @taddcrockett in https://github.com/privacysandbox/privacy-sandbox-dev-support/issues/149#issuecomment-2048192104_

**Comment by linnan-github** [comment]
@taddcrockett Thanks for reporting. Two quick questions, what API surface did you use for registration? And did you see `Attribution-Reporting-Eligible` header in the request? Thanks.

**Comment by taddcrockett** [comment]
@linnan-github I used `XMLHttpRequest` using `attributionReporting` options and I didn't see `Attribution-Reporting-Eligible` either.

I just saw in the [docs](https://developers.google.com/privacy-sandbox/relevance/attribution-reporting/register-attribution-trigger#required_and_optional_attributes) that `attributionsrc` is required for these headers to be added and to support app-web measurement. Does `XMLHttpRequest` with `attributionReporting` not also support adding these headers?

**Comment by apasel422** [comment]
@taddcrockett Would you mind providing a snippet of JavaScript showing exactly how you're using `XMLHttpRequest`?

**Comment by vsanka14** [comment]
Hi @apasel422, thanks for assisting us in this issue. Please allow me to share a snippet of how we are using XMLHttpRequest:

```
const setAttributionReportingOptions = (_http) => {
 if ('setAttributionReporting' in _http) {
  _http.setAttributionReporting({
      eventSourceEligible: false,
      triggerEligible: true,
  });
 }
}

const makeHTTPRequest = async (
  method: string,
  url: string,
) => {
  const http = new XMLHttpRequest();
  http.open(method, url, true);

  http.onreadystatechange = () => {
    if (http.readyState === 1) {
      // Here is where the attribution reporting options are set for the XMLHttpRequest
      setAttributionReportingOptions(http);
    }
  };

  http.send();
};
```

**Comment by apasel422** [comment]
@vsanka14 Can you try calling `setAttributionReportingOptions` immediately after calling `open` instead of doing it in the `onreadystatechange` callback?

```js
const http = new XMLHttpRequest();
http.open(method, url, true);
setAttributionReportingOptions(http);
http.send();
```

**Comment by vsanka14** [comment]
@apasel422 Sure I can do that. Should I expect to see the `Attribution-Reporting-Eligible` in the request headers when the attribution reporting options are set?

We were doing the approach you suggested initially but had to change it when we started seeing `Failed to execute 'setAttributionReporting'` errors.

**Comment by apasel422** [comment]
Yes, you should see both headers when you use my suggestion, and I don't think any `Failed to execute` error should occur as long as you are feature-checking properly, which I think would be slightly more robust as

```js
if (typeof _http.setAttributionReporting === 'function') {
  _http.setAttributionReporting(...);
}
```

And by the way, I'm not sure that your use of `async` is exactly right with the `makeHTTPRequest` function, as `XMLHttpRequest` isn't promise-based. If you want to use Attribution Reporting with promises, you may find `fetch` easier to use.

**Comment by vsanka14** [comment]
Hey @apasel422 moving the setAttributionReportingOptions outside of the `readyState == 1` if block seems to have done the trick. I see the `Attribution-Reporting-Eligible` in the request headers with the suggested change. Thanks a lot for the help.

> And by the way, I'm not sure that your use of async is exactly right with the makeHTTPRequest function, as XMLHttpRequest isn't promise-based. If you want to use Attribution Reporting with promises, you may find fetch easier to use.

Re the async usage, you're right about the snippet the real code however does actually wrap the return value in a promise 😄. And we are also doing a feature check as described [here](https://developers.google.com/privacy-sandbox/relevance/attribution-reporting/getting-started#dont_forget_feature_detection) before making the XHR request.

> Yes, you should see both headers when you use my suggestion, and I don't think any Failed to execute error should occur as long as you are feature-checking properly, which I think would be slightly more robust as

Isn't it reasonable to assume `setAttributionReporting` is always a function if it exists? And as stated above we're also doing a feature check. The issue seemed to stem from an intermittent race condition, where `setAttributionReporting` would attempt execution before the ready state was open. However, it now appears that explicitly checking for the ready state to be open is occurring too late to actually set the request headers. Could you provide insight into the sequence of execution in this scenario?

**Comment by vsanka14** [comment]
I think I may have something here: What I missed sharing in the initial snippet was that we were invoking `setRequestHeader` before `setAttributionReporting` (updated now). Seems like this causes the request headers to not be sent for some reason. Switching the order of invocations fixed the issue.

**Comment by apasel422** [comment]
> Isn't it reasonable to assume `setAttributionReporting` is always a function if it exists?

In Chromium, it's reasonable to assume, yes, though it's possible for other JS (including extensions) to modify it. There's no harm in ensuring it's a function before trying to call it, but what you have is fine in the typical case.

> The issue seemed to stem from an intermittent race condition, where `setAttributionReporting` would attempt execution before the ready state was open. However, it now appears that explicitly checking for the ready state to be open is occurring too late to actually set the request headers. Could you provide insight into the sequence of execution in this scenario?

I'm not an expert on `XMLHttpRequest`, but I do know that `setAttributionReporting` needs to be called strictly before `send`, which I'm not sure was the case with the version using `onreadystatechange`, as by the time you have added the listener the request may *already be open*. (In other words, you may have missed the change corresponding to becoming open.)

> What I missed sharing in the initial snippet was that we were invoking `setRequestHeader` before `setAttributionReporting` (updated now). Seems like this causes the request headers to not be sent for some reason. Switching the order of invocations fixed the issue.

This is surprising to me, so I will have to investigate.

All this said, I strongly encourage using `fetch` instead of `XMLHttpRequest`, if possible, due to its more ergonomic API.

I will close this issue for now, but feel free to file a new one if you encounter other issues.
