### ISSUE TITLE
3PCD Deprecation Trial Expiration and the Updated Timeline to 2025

### ISSUE THREAD

**Issue by bretticus-mc** [privacysandbox/privacy-sandbox-dev-support#338]
Hello,

Will the 3PCD Deprecation Trial expiration date be pushed back to sync with the [updated timeline](https://developers.google.com/privacy-sandbox/3pcd) to Q2 2025? If so, will we need to register for and add a new Deprecation Trial token or would the existing token expiration be automatically updated?

**Comment by samdutton** [comment]
Apologies for the very long delay in responding!

Please see [Updates to temporary third-party cookie exceptions in Chrome](https://developers.google.com/privacy-sandbox/blog/3pc-exceptions-update) for more information regarding the status of the 3PCD deprecation trials.

In particular: 

> Chrome is extending the grace period that allows sites and services demonstrating user-facing, non-ads breakage to continue to access third-party cookies. Origins using this grace period don't need to deploy deprecation trial tokens; origins that have already deployed tokens don't need to keep them in place. We plan to maintain the grace period at least until we introduce a new experience in Chrome that lets people make an informed choice that applies across their web browsing.

Hope that helps.

**Comment by samdutton** [comment]
Closing this as completed, but feel free to reopen.
