### ISSUE TITLE
Broadcast Channel and iframes

### ISSUE THREAD

**Issue by thielium** [privacysandbox/privacy-sandbox-dev-support#339]
Hello!

[Based on the developer documentation](https://developers.google.com/privacy-sandbox/3pcd/storage-partitioning), the Privacy Sandbox disables communication via Broadcast Channel for a few cases. In particular, communication from a top-level browsing context to iframes of the same origin, but embedded in third-party sites, is no longer viable.

This makes it very challenging to synchronize browser tabs in authentication flows (a use case where server-side implementation is tricky due to a lack of user identity -- we can't lean on the server to broadcast to a user as the user is not yet known to the server).

Example:

- User opens Tab 1
- User opens embedded application in Tab 2
- User logs into Tab 1
- **(?)** How do we signal to Tab 2 that they are authenticated?

This may seem contrived, but it's not uncommon for applications to embed in enterprise contexts (e.g. Atlassian iframes may contain any number of embedded enterprise products).

Do any affordances exist for cases like this?

**Comment by cfredric** [comment]
Yes, this is supported by the Storage Access API in Chrome (not yet in other browsers, as far as I know). Specifically, please see https://github.com/privacycg/saa-non-cookie-storage (or the [spec](https://privacycg.github.io/saa-non-cookie-storage/#document-changes) for nitty-gritty details) to see how this could work for BroadcastChannel. This functionality is enabled by default in [Chrome M125](https://chromiumdash.appspot.com/commit/3b049d2c809f9f171696ac870e0b119932c3d204) and later.

**Comment by thielium** [comment]
Thank you for the helpful links, quick response, and thorough answer. I can close the issue, much obliged!
