### ISSUE TITLE
Attribution-Reporting-Support header values

### ISSUE THREAD

**Issue by taddcrockett** [privacysandbox/privacy-sandbox-dev-support#344]
Hello team, can you clarify what the meaning of `Attribution-Reporting-Support: os=web` is? This isn't discussed anywhere in the [docs](https://github.com/WICG/attribution-reporting-api/blob/main/app_to_web.md) but we are seeing it in our testing. 

<img width="614" alt="image" src="https://github.com/privacysandbox/privacy-sandbox-dev-support/assets/14481469/cc778786-8ce6-4164-bf04-4e8522e48167">

**Comment by apasel422** [comment]
`os=web` is an example of a [greased header value](https://wicg.github.io/attribution-reporting-api/#obtain-a-dictionary-structured-header-value):

> The user agent MAY "[grease](https://httpwg.org/specs/rfc8941#specify)" the dictionary structured headers according to the preceding algorithm to help ensure that recipients use a proper structured header parser, rather than naive string equality or contains operations, which makes it easier to introduce backwards-compatible changes to the header definition in the future. Including the allowed keys as dictionary values or parameters helps ensure that only the dictionary’s keys are interpreted by the recipient. Likewise, shuffling the dictionary members helps ensure that, e.g., "key1, key2" is treated equivalently to "key2, key1".

For the `Attribution-Reporting-Support` header, only the dictionary **keys** (not values) have meaning, so in this case you should interpret the header as indicating that there is only `os` support and nothing else.

This is mentioned for the `Attribution-Reporting-Eligible` header [in the event-level explainer](https://github.com/WICG/attribution-reporting-api/blob/main/EVENT.md#registration-requests), but you're right that it isn't mentioned in the cross-app-and-web explainer for the `Attribution-Reporting-Support` header. I will rectify that.

**Comment by taddcrockett** [comment]
Great, thanks for the explantaion @apasel422, closing the ticket
