### ISSUE TITLE
Protected Audience for Android Rendering Clarifications

### ISSUE THREAD

**Issue by thegreatfatzby** [privacysandbox/privacy-sandbox-dev-support#347]
Hoping to dive in on two elements of rendering in Protected Audience API for Android as I think different docs are implying slightly different things.. 

From the [Google Developers](https://developers.google.com/privacy-sandbox/relevance/protected-audience/android/bidding-and-auction-integration) I think I'm seeing two interesting deviations from PAAPI for Web:
1. I don't see k-anonymity mentioned anywhere. I see k-anon inconsistently mentioned.
2. The returned renderUrl can be decrypted, it seems to be implied to plain text.

EDIT: so I do see k-anon mentioned in one Android specific doc, the [Integration Guide](https://developers.google.com/privacy-sandbox/relevance/protected-audience/android/integration-guide#addata_list). 
However...in the main [BA design](https://github.com/privacysandbox/protected-auction-services-docs/blob/main/bidding_auction_services_system_design.md) explainer [k-anon](https://github.com/privacysandbox/protected-auction-services-docs/blob/main/bidding_auction_services_system_design.md#k-anonymity-integration) and android are both explicitly mentioned...however other Android elements such as inference service are not, so I'm not clear which one is "canonical". I also don't see k-anon mentioned anywhere in the Protected App Signals developer [overview](https://developers.google.com/privacy-sandbox/relevance/protected-audience/android/protected-app-signals) or [guide](https://developers.google.com/privacy-sandbox/relevance/protected-audience/android/protected-app-signals-developer-guide).

So I guess my question is whether Sellers will be able to both a) display ads with non-k-anon renderUrls, whether returned from PAAPI for Android of PPAPI, and then b) whether they can view that URL in plain text.

EDIT: after finding the integration guide I'm hoping that the answer to (a) is that k-anon will be enforced, and the docs just currently need to be updated and taken with a grain of salt in the meantime...but still curious about (b)

**Comment by cshmerling** [comment]
K-anon will be enforced on Android as it is for Web. While out of date, you can see this is part of the timeline published [on the explainer](https://developers.google.com/privacy-sandbox/private-advertising/protected-audience/android#timeline). Updated dates and more information to follow.

As for (b), yes, the render URI can be read as plaintext.

**Comment by cshmerling** [comment]
Marking this as resolved, but please feel free to re-open or raise a new issue if you have further questions
