### ISSUE TITLE
Error with Permissions-Policy header: Unrecognized feature: 'ch-ua-form-factor'.

### ISSUE THREAD

**Issue by PhilippeQUERCY** [privacysandbox/privacy-sandbox-dev-support#349]
Error with Permissions-Policy header: Unrecognized feature: 'ch-ua-form-factor'.

**Comment by PhilippeQUERCY** [comment]
Bonjour,

Origine du problème ? Comment le régler ?

Merci

**Comment by miketaylr** [comment]
This appears to be spam, closing.
