### ISSUE TITLE
Clarification regarding varying frequency and number of reports in event level reporting

### ISSUE THREAD

**Issue by ydennisy** [privacysandbox/privacy-sandbox-dev-support#354]
Hello!

I am looking at the following [document](https://github.com/WICG/attribution-reporting-api/blob/main/EVENT.md#optional-varying-frequency-and-number-of-reports).

1. I would like to clarify what the exact effect of changing `max_event_level_reports` will be, my understanding is that increasing this number will increase randomised trigger rate, but is it clear by how much? Some examples would be lovely!
2. In the `event_report_windows` I am completely lost, whilst I understand the basics of what has been written - I am unable to understand what effect this will have on the data, it would be extremely helpful for a few concrete examples and use cases on how setting various windows will affect the data receipt.

Thanks in advance!!

**Comment by apasel422** [comment]
> 1. I would like to clarify what the exact effect of changing `max_event_level_reports` will be, my understanding is that increasing this number will increase randomised trigger rate, but is it clear by how much? Some examples would be lovely!

In addition to the effect on noise, changing this value also (as its name implies) limit the number of event-level reports that the particular source can produce. To see the effect on noise, you can experiment with different values using our header validator, e.g. with [ a limit of 1](https://wicg.github.io/attribution-reporting-api/validate-headers?header=source&json=%7B%22destination%22%3A%22https%3A%2F%2Fx.example%22%2C%22max_event_level_reports%22%3A1%7D&source-type=event&flex=false) vs [a limit of 2](https://wicg.github.io/attribution-reporting-api/validate-headers?header=source&json=%7B%22destination%22%3A%22https%3A%2F%2Fx.example%22%2C%22max_event_level_reports%22%3A2%7D&source-type=event&flex=false).

> 2. In the `event_report_windows` I am completely lost, whilst I understand the basics of what has been written - I am unable to understand what effect this will have on the data, it would be extremely helpful for a few concrete examples and use cases on how setting various windows will affect the data receipt.

This field affects the times at which event-level reports, if any, will be sent to you: the times themselves and the number of such times.

For example, a (partial) source configuration occurring at time `T` like:

```json
{"event_report_windows": {"end_times": [3600, 7200]}}
```

means that triggers attributed to that source between 0 and 3600 seconds after `T` will be reported at `T + 3600 seconds`, while triggers that occur between 3600 and 7200 seconds after `T` will be reported at `T + 7200 seconds`. Any triggers that occur after 7200 seconds will be rejected.

In addition to the `end_times` field, the optional `start_time` field allows you to set the initial range to some offset greater than 0 seconds from `T`: Any triggers received before start_time will likewise be rejected.

Does that clarify things? I know that our documentation is in need of some cleanup, and I agree that examples would help.

You can read a bit more about this in https://developers.google.com/privacy-sandbox/relevance/attribution-reporting/custom-report-windows, though unfortunately it is written using only the older `event_report_window` (note the lack of a trailing `s`) field, which doesn't allow as much customization as the one we are discussing in this issue.

**Comment by apasel422** [comment]
@ydennisy Just following up on this.
