### ISSUE TITLE
is `Path=/` still required for the partitioned cookies?

### ISSUE THREAD

**Issue by islishude** [privacysandbox/privacy-sandbox-dev-support#359]
https://developers.google.com/privacy-sandbox/blog/chips-origin-trial#additional_details

it says that the `path=/` is required, but I didn't find it in the MDN.

https://developer.mozilla.org/en-US/docs/Web/Privacy/Privacy_sandbox/Partitioned_cookies

**Comment by samdutton** [comment]
`path=/` no longer required.

https://github.com/privacycg/CHIPS/pull/49

Thanks for the heads-up — I've submitted an update to the blog post.
