### ISSUE TITLE
What will consent banner look

### ISSUE THREAD

**Issue by Dory998** [privacysandbox/privacy-sandbox-dev-support#362]
Once google removes support for 3PC what will a consent banner look like? I'm.guessing as still have 1st party cookies if could look kind of similar with strictly necessary, functional still existing? And perhaps performance cookies like GA being deprecated. I do wonder what privacy companies like OneTrust and Trustarc are doing to work with Google Privacy Sandbox. I'm proposing internally we replace cookie policy pages with privacy trust policy pages. Cookies will remain post Googles changes but they will taste a bit different

**Comment by samdutton** [comment]
Hi @Dory998 — thanks for your question, and apologies for the delay in responding.

The Privacy Sandbox [Privacy-related compliance FAQs](https://developers.google.com/privacy-sandbox/overview/privacy-compliance-faqs) provides information about consent and ePrivacy.

We recommend that you contact your Consent Management Platform (CMP) to find out more about future consent banner requirements.

**Comment by samdutton** [comment]
I'm closing this as completed, as there hasn't been any follow up in several weeks, but feel free to reopen if necessary.
