### ISSUE TITLE
can a user opt-out from this 1% third party cookie deprecation

### ISSUE THREAD

**Issue by kumarrishav** [privacysandbox/privacy-sandbox-dev-support#366]
Let's say, I am using an app but because of third-party cookie deprecation, I have a broken experience. Can i (as a user) opt-out of this 1% Third-party cookie deprecation (via some setting/flag) so that I can continue using the app? Or is it only the third party or first party can fix it (either via deprecation trail or implementing other solutions)?

Will "enabling allowing third party cookies" in privacy and security have any impact?

**Comment by samdutton** [comment]
Hi @kumarrishav — thanks for the question.

A user who is in the [1% group](https://developers.google.com/privacy-sandbox/blog/cookie-countdown-2024jan), for which third-party cookies are restricted by default, can allow third-party cookies for an individual site by using the eye icon to add the site to the list of sites allowed to use third-party cookies. 

Alternatively, a site can be added directly from `chrome://settings/trackingProtection`. Access to third-party cookies can be renewed when the exception expires.

Chrome Enterprise installations can also add sites to the [`CookiesAllowedForUrls`](https://developers.google.com/privacy-sandbox/3pcd/temporary-exceptions/chrome-enterprise#allow_third-party_cookies_from_specific_sites_or_urls) policy.

<img width="1196" alt="image" src="https://github.com/privacysandbox/privacy-sandbox-dev-support/assets/205226/c6c7f97f-9623-4864-976d-cf930cc0fbe5">
<img width="1196" alt="image" src="https://github.com/privacysandbox/privacy-sandbox-dev-support/assets/205226/53c80f34-54e3-401c-84ee-1070f82f068d">

**Comment by samdutton** [comment]
No further response in two weeks, so closing this issue, but feel free to reopen.
