### ISSUE TITLE
Seeking Clarification on support end date and implementation deadline for Depreciation tokens

### ISSUE THREAD

**Issue by rbolisetty** [privacysandbox/privacy-sandbox-dev-support#367]
Hi,

We have a couple of Depreciation tokens assigned to us and we would like to get clarification on the deadline to implement these tokens.

According to https://developers.google.com/privacy-sandbox/blog/third-party-cookie-deprecation-trial, the support for Depreciation tokens was initially set to end on December 27, 2024. However, the latest update states that Google has extended the phase-out date until Q1 2025. We would like to understand if the deadline to implement these tokens will also be pushed back.

Additionally, we are curious about what will happen to the support end date for Depreciation tokens – will that also be extended?

**Comment by docutim** [comment]
I'm also curious about how the 3p cookie deprecation timeline has changed.

**Comment by GopiChandRaju** [comment]
I am also confused about the timelines. 
Can you please clarify on phase-out date( Q1 2025) and Depreciation token(December 27, 2024) ?
Should we keep efforts on Depreciation token implementation if the phase-out time it self starts on Q1 2025 ?

**Comment by muhdashiq** [comment]
I share the concerns raised regarding the timeline for Depreciation tokens and the phase-out date for third-party cookies.

To reiterate, the initial support end date for Depreciation tokens was set for December 27, 2024. However, with the recent update from Google extending the phase-out of third-party cookies to Q1 2025, we need clarity on a couple of points:

1. Will the implementation deadline for Depreciation tokens also be extended in line with the new phase-out date?
2. If the phase-out begins in Q1 2025, should we continue our efforts to implement Depreciation tokens by the original deadline, or will there be a new deadline?

Understanding these timelines is crucial for our planning and resource allocation. Any clarification on these points would be greatly appreciated.

Thank you.

**Comment by ashu66867** [comment]
+1
What is the third party cookie phase out date?
And what will be the validity timeline for depreciation tokens?

**Comment by pk-docu** [comment]
Timelines are bit confusing on 3p-cookie deprecation. Do we need to work on implementing Deprecation Token before starting implementing the CHIPS?

**Comment by gregtalarico** [comment]
We are also concerned about the timelines and would like someone on the Chrome/Privacy Sandbox team to confirm the dates for the Grace Period, Deprecation Trial Token Expiration and 3PC phase out. 

In the 4/23/24 [Privacy Sandbox Update](https://privacysandbox.com/news/update-on-the-plan-for-phase-out-of-third-party-cookies-on-chrome/) and the [CMA report](https://assets.publishing.service.gov.uk/media/662baa3efee48e2ee6b81eb1/1._CMA_Q1_2024_update_report_on_Google_Privacy_Sandbox_commitments.pdf) that is linked in the post, its stated that Chrome will not complete the 3PC phase out in the second half of Q4 '24 and will now proceed with phase out in Q1 '25. However, it does not seem that the grace period not token expiration   dates have been adjusted to match up with this new timeline. Our grace period end date is 8/30/24 and the token expiration is still set at 12/27/24. 

Neither of those dates seems consistent with restarting phaseout in Q1 '25.

Please advise

**Comment by samdutton** [comment]
Thanks for the questions. 

The timeline for third-party cookie phaseout is available from [privacysandbox.com/open-web](https://privacysandbox.com/open-web/). Subject to addressing any remaining competition concerns of the UK's Competition and Markets Authority, we envision proceeding with third-party cookie deprecation starting in early 2025.

Chrome announced [changes to the grace period](https://developers.google.com/privacy-sandbox/blog/grace-period-update?hl=en) earlier this week and intends to revise the deprecation trial end date. Changes to the deprecation trial will be announced on the [Privacy Sandbox developer blog](https://developers.google.com/privacy-sandbox/blog).

> Do we need to work on implementing Deprecation Token before starting implementing the CHIPS?

CHIPS can be implemented without waiting for deprecation trial implementation, but the decision on how to prioritise effort for deprecation trial participation and/or CHIPS is up to each site owner.

**Comment by rbolisetty** [comment]
Thanks for the clarification.

> CHIPS can be implemented without waiting for deprecation trial implementation, but the decision on how to prioritise effort for deprecation trial participation and/or CHIPS is up to each site owner.

If the deprecation trial ends before the phaseout, why should site owners put effort into implementing it?

**Comment by miketaylr** [comment]
@rbolisetty as Sam has stated, each site owner has to make decisions that make sense for their own contexts.

> ... and intends to revise the deprecation trial end date.

And it seems likely that an extension for the deprecation trial will happen so it doesn't expire before phaseout (as Sam stated).

> If the deprecation trial ends before the phaseout, why should site owners put effort into implementing it?

If deploying a deprecation trial token is more effort than making ones site ready for 3P cookie deprecation, I'm not sure why a site would choose to do that. 

The general point remains - each site is different, and will have to make these decisions based on their own needs and constraints.

**Comment by rbolisetty** [comment]
Thanks for the clarification @miketaylr!
is there an issue/ticket I can follow to get an update when Google updates the DT expiry?

**Comment by miketaylr** [comment]
I am not aware of any issue or ticket - but DT renewals are approved on the [public blink-dev mailing list](https://groups.google.com/a/chromium.org/g/blink-dev) (though, it gets a lot of traffic that you may not be interested in!). If any renewal does happen, I would expect there to be a blog post and/or updates to the existing documentation so the ecosystem can be aware.
