### ISSUE TITLE
Can register source and register trigger be served by different sub domains?

### ISSUE THREAD

**Issue by amirmatar** [privacysandbox/privacy-sandbox-dev-support#378]
Hey,

Is there a problem sending register source and register trigger to different sub domains?
Will Chrome be able to attribute the register source event to the register trigger event?

Amir

**Comment by apasel422** [comment]
The reporting *origin* must match in order for the trigger to be attributed to the source.

**Comment by apasel422** [comment]
Are you able to work around this requirement using redirects? For example, if you currently register sources at `https://foo.mydomain.example/x` and triggers at `https://bar.mydomain.example/y` you can have those URLs redirect to `https://register.mydomain.example/source` and `https://register.mydomain.example/trigger`. The reporting origin in that case will be `https://register.mydomain.example`.

**Comment by apasel422** [comment]
@amirmatar Just following up on this.

**Comment by amirmatar** [comment]
I was able to make it work using redirects but I don't think this is a good solution because it duplicates the amount of calls between the browser and our servers. I believe many ad networks have different subdomains for click and conversion endpoints so either they add these redirects or they need to change their topology. 
Can you please explain why can't Chrome attribute conversions to events based on the eTLD+1 domain?

**Comment by apasel422** [comment]
We try to scope everything to origin for security reasons. If you're concerned that the redirect approach isn't performant enough, please consider filing an issue on https://github.com/WICG/attribution-reporting-api in which we can discuss alternative options.
