### ISSUE TITLE
Time for disabling third-party cookies

### ISSUE THREAD

**Issue by xiaodingmao233** [privacysandbox/privacy-sandbox-dev-support#389]
https://developers.google.cn/privacy-sandbox/3pcd/prepare/prepare-for-phaseout?authuser=0&hl=cs

Hello, I found this from the above website. I would like to know about Chrome's timeline for disabling third-party cookies. It is understood that only 1% of the grayscale test has been conducted now. Is Q3 directly disabled in full. Do you have a specific time?

**Comment by xiaodingmao233** [comment]
https://developers.google.cn/privacy-sandbox/blog/cookie-countdown-2024jan?authuser=0000&hl=zh-cn

https://developers.google.cn/privacy-sandbox/3pcd/prepare/prepare-for-phaseout?authuser=0&hl=cs

These two websites have inconsistent descriptions. One says they will be fully available in Q3, while the other says they will gradually be fully available starting in 2025. What is the current real plan?

**Comment by miketaylr** [comment]
Thanks for the issue (cc @rowan-m for the incorrect timeline in the cookie-countdown-2024jan article).

> One says they will be fully available in Q3, while the other says they will gradually be fully available starting in 2025.

https://developers.google.cn/privacy-sandbox/3pcd/prepare/prepare-for-phaseout is correct. See also https://privacysandbox.com/open-web/#the-privacy-sandbox-timeline

**Comment by xiaodingmao233** [comment]
Received, thank you for your answer

**Comment by samdutton** [comment]
Thanks @xiaodingmao233 !

I've added a warning to https://developers.google.com/privacy-sandbox/blog/cookie-countdown-2024jan. 

FWIW we update articles, but generally avoid editing blog posts after they've been published (since they're like items of news that belong to a moment in time). Having said that, it's not obvious to readers what's a "blog post" and what's an "article"!

**Comment by samdutton** [comment]
Closing this as completed, but feel free to reopen.
