### ISSUE TITLE
Are Enterprise Chrome customers included in the 1% testing phase?

### ISSUE THREAD

**Issue by bretticus-mc** [privacysandbox/privacy-sandbox-dev-support#390]
I'm reading [this page](https://developers.google.com/privacy-sandbox/3pcd/temporary-exceptions/chrome-enterprise). 
> As with the majority of Chrome experiments, most Chrome Enterprise end users will be excluded from the [1% third-party cookie restrictions](https://developers.google.com/privacy-sandbox/blog/cookie-countdown-2024jan) automatically.

Does this mean that Enterprise Chrome users will be excluded from the 1% 3PCD testing group by default? Or is there a chance Enterprise Chrome users will be included?

**Comment by krgovind** [comment]
@bretticus-mc Our enterprise environment detection mechanism may not work in all scenarios; so depending on your configuration/platform it is possible that some enterprise users are included in the experiment. We would recommend proactively deploying the policies mentioned on the page if your organization relies on web applications that depend on third-party cookie support.

**Comment by bretticus-mc** [comment]
I see. Will there be a similar attempt to exclude Enterprise Chrome users when Chrome ramps up its rollout from 1% to 100%?
