### ISSUE TITLE
Is there a command-line switch to enable storage partitioning?

### ISSUE THREAD

**Issue by bretticus-mc** [privacysandbox/privacy-sandbox-dev-support#397]
We'd like to update our testing suite to cover customers who disable storage partitioning. Is there a Chromium flag that supports this? If not, could one be added?

**Comment by wanderview** [comment]
You should be able to use `--disable-features="ThirdPartyStoragePartitioning"`.  If you have other features disabled use comma separation.

**Comment by miketaylr** [comment]
And `--enable-features="ThirdPartyStoragePartitioning"` for the opposite case.

**Comment by bretticus-mc** [comment]
Thank you!
