### ISSUE TITLE
Existing cookies jar when a browser is part of mode b (1%)

### ISSUE THREAD

**Issue by omriariav** [privacysandbox/privacy-sandbox-dev-support#414]
Hi,

When you add a browser to mode b, the 1% without 3PC, will the current cookies jar (1PC, 3PC, localstorage...) stay or is it wiped out? 

I believe that for UX, it will be kept until the user clears them, but I want to confirm.

Please advise,
Thanks,
Omri.

**Comment by johannhof** [comment]
They will stick around. "Third-party" cookies are technically your first-party cookies (and storage), just accessed from a cross-site / third-party context. They will still be accessible to your own first-party sites.

**Comment by omriariav** [comment]
Thank you
