### ISSUE TITLE
Chrome sending Samesite=Lax or no samesite attribute as third party cookies

### ISSUE THREAD

**Issue by judielaine** [privacysandbox/privacy-sandbox-dev-support#433]
In looking at cookies being sent as third party with Chrome i noticed some with `SameSite=Lax` (and those that default to `SameSite=Lax`) were being sent cross site. I filed  https://issues.chromium.org/issues/373443097  and have been told Chrome is working as designed as " SameSite=Lax allows Chrome to send the cookie with these top-level navigations; and in the cases where those navigations are 3P, the cookies will show as 3P."

This seems different from the advice given in the privacy sandbox as well as with https://httpwg.org/http-extensions/draft-ietf-httpbis-rfc6265bis.html#name-mashups-and-widgets . Is Chrome's current behavior different than what is planned? That is, at some point only `SameSite=None` will be sent cross-site but currently `SameSite=Lax` is also sent as same site? 

Thanks for clarity.

The issue filed with Chromium is reproduced in part below.

### Summary

Cookies with SameSite=Lax or without a SameSite attribute sent as third party

### Steps to reproduce the problem

    Turn on developer tools, optionally with "Privacy Sandbox" on
    Visit https://www.nytimes.com/
    In Dev tools, click Application tab, Storage|Cookies|https://www.nytimes.com/ in left hand menu. Sort table by "SameSite" column. Look at those with value "Lax". I see one cookie .google.com domain Name AEC that is being sent. To double check my interpretation i use the "Privacy Sandbox" tab Privacy Sandbox|Cookies|https://www.nytimes.com/ and looked for the cookie named AEC. The scope is listed as "Third Party."

For more definitive test,

    Turn on developer tools, optionally with "Privacy Sandbox" on
    clear cookies
    Visit OCLC.org, accept only necessary cookies. Using Dev tools note the ga* cookie set SameSite=Lax
    Visit search.worldcat.org, accept only necessary cookies.
    Using developer tools as in the first reproduction, look at the ga* cookies. I have two. one in a first site scope, but also one in a "Third Party" scope from oclc.org.

### Problem Description

More cookies are sent in a third party context than expected. I would like to limit cookies from the oclc.org so they aren't sent as third party cookies. I understand the ones marked as SameSite=None will be sent as third party. I would expect the cookies marked as Lax would not be sent by the browser.

My expectation is that Chrome would only send LAX cookies when the site in the cookie matches the top level site, but not when it was a cross-site call. (In the second reproduction, instructions the cover art for books displayed at the worldcat.org site is displayed from a oclc.org address.) Since two of the cookies are SameSite=None, i expect those cookies to be sent. I did not expect the oclc.org cookie marked SameSite=Lax to be sent while at the worldcat.org site.

I'll admit to finding the evolving RFC less than clear about third party usage of cookies at https://httpwg.org/http-extensions/draft-ietf-httpbis-rfc6265bis.html#name-the-samesite-attribute-2 "developers may set the SameSite attribute in a "Lax" enforcement mode that carves out an exception which sends same-site cookies along with cross-site requests if and only if they are top-level navigations which use a "safe" (in the [HTTP] sense) HTTP method," is clear about when first party cookies marked Lax will be sent (eg: won't be sent on a POST).

https://httpwg.org/http-extensions/draft-ietf-httpbis-rfc6265bis.html#name-mashups-and-widgets "The Lax and Strict values for the SameSite attribute are inappropriate for some important use-cases. In particular, note that content intended for embedding in cross-site contexts (social networking widgets or commenting services, for instance) will not have access to same-site cookies, " seems pretty clear, though, that SameSite=Lax would NOT be sent as a thirdparty cookie.
Additional Comments

I assume this is a regression, but i haven't poked at cookies with this intensity before. Comparison with Firefox is hard because i am limiting third party cookies, i think.

I've checked my browser to see if it had any legacy same-site flags and found none. My browser is set to with the radio button to [*] Block third-party cookies in Incognito mode

**Comment by johannhof** [comment]
Hi @judielaine, thanks for raising this. There could be a bug and/or confusing UX with DevTools here, let's follow up again on the bug, I don't think we need this issue as well. Per my testing no SameSite=Lax cookies are sent, which is the correct behavior, as you've assessed.

@samdutton can you please close this? :)

**Comment by samdutton** [comment]
@johannhof 

> @samdutton can you please close this?

Sure — closing here, given follow-up on https://issues.chromium.org/issues/373443097.
